export interface LeaderboardEntry {
  /**
   * What the model's own vendor charges to run it through their API, as Artificial Analysis
   * quoted it. Not what fal charges us - fal resells several of these for a fraction of the
   * price. For our cost, read `falPricing` on the model in `models.ts`.
   */
  apiPricing?: string;
  creator: string;
  elo: number;
  isCurrent?: boolean;
  model: string;
  rank: number;
  routableModelId?: string;
}

export interface LeaderboardSnapshot {
  capturedAt: string;
  entries: LeaderboardEntry[];
  source: string;
}

export const IMAGE_TEXT_TO_IMAGE_TOP_20: LeaderboardSnapshot = {
  capturedAt: "2026-10-07",
  entries: [
    {
      apiPricing: "$210.7 /1k imgs",
      creator: "OpenAI",
      elo: 1198,
      isCurrent: true,
      model: "GPT Image 2.5 Sunburst (max)",
      rank: 1,
      routableModelId: "sunburst",
    },
    {
      apiPricing: "$210.7 /1k imgs",
      creator: "OpenAI",
      elo: 1191,
      isCurrent: true,
      model: "GPT Image 2.5 Flare (max)",
      rank: 2,
      routableModelId: "flare",
    },
    {
      apiPricing: "$211.0 /1k imgs",
      creator: "OpenAI",
      elo: 1172,
      isCurrent: true,
      model: "GPT Image 2 (high)",
      rank: 3,
      routableModelId: "gpt2",
    },
    {
      apiPricing: "$60.0 /1k imgs",
      creator: "SpaceXAI",
      elo: 1156,
      isCurrent: true,
      model: "Grok Imagine Image 2.0",
      rank: 4,
      routableModelId: "grok-image-2",
    },
    {
      apiPricing: "$38.9 /1k imgs",
      creator: "Microsoft AI",
      elo: 1151,
      isCurrent: true,
      model: "MAI-Image-2.6",
      rank: 5,
    },
    {
      apiPricing: "$67.0 /1k imgs",
      creator: "Google",
      elo: 1126,
      isCurrent: true,
      model: "Nano Banana 2 (Gemini 3.1 Flash Image)",
      rank: 6,
      routableModelId: "banana2",
    },
    {
      apiPricing: "$10.0 /1k imgs",
      creator: "Meta",
      elo: 1115,
      isCurrent: true,
      model: "Muse Image",
      rank: 7,
    },
    {
      apiPricing: "$133.0 /1k imgs",
      creator: "OpenAI",
      elo: 1107,
      isCurrent: true,
      model: "GPT Image 1.5 (high)",
      rank: 8,
      routableModelId: "gpt",
    },
    {
      apiPricing: "$19.5 /1k imgs",
      creator: "Microsoft AI",
      elo: 1105,
      isCurrent: true,
      model: "MAI-Image-2.6-Flash",
      rank: 9,
    },
    {
      apiPricing: "$48.1 /1k imgs",
      creator: "Microsoft AI",
      elo: 1104,
      isCurrent: true,
      model: "MAI-Image-2.5",
      rank: 10,
      routableModelId: "mai-image-2.5",
    },
    {
      apiPricing: "$134.0 /1k imgs",
      creator: "Google",
      elo: 1102,
      isCurrent: true,
      model: "Nano Banana Pro (Gemini 3 Pro Image)",
      rank: 11,
      routableModelId: "banana",
    },
    {
      apiPricing: "$108.5 /1k imgs",
      creator: "Microsoft AI",
      elo: 1100,
      isCurrent: true,
      model: "MAI-Image-2.5-Pro",
      rank: 12,
      routableModelId: "mai-image-2.5-pro",
    },
    {
      apiPricing: "$33.6 /1k imgs",
      creator: "Google",
      elo: 1095,
      isCurrent: true,
      model: "Nano Banana 2 Lite (Gemini 3.1 Flash Lite Image)",
      rank: 13,
      routableModelId: "banana2-lite",
    },
    {
      apiPricing: "$40.0 /1k imgs",
      creator: "Alibaba",
      elo: 1088,
      isCurrent: true,
      model: "Qwen-Image-3.0-Pro",
      rank: 14,
    },
    {
      apiPricing: "$90.0 /1k imgs",
      creator: "ByteDance Seed",
      elo: 1081,
      isCurrent: true,
      model: "Seedream 5.0 Pro",
      rank: 15,
      routableModelId: "seedream5",
    },
    {
      apiPricing: "$30.0 /1k imgs",
      creator: "Alibaba",
      elo: 1075,
      isCurrent: true,
      model: "Qwen-Image-3.0",
      rank: 16,
      routableModelId: "qwen3",
    },
    {
      apiPricing: "$50.0 /1k imgs",
      creator: "SpaceXAI",
      elo: 1046,
      isCurrent: true,
      model: "grok-imagine-image-quality",
      rank: 17,
    },
    {
      apiPricing: "No API available",
      creator: "Alibaba",
      elo: 1035,
      isCurrent: true,
      model: "Qwen-Image-2.1",
      rank: 18,
    },
    {
      apiPricing: "$20.0 /1k imgs",
      creator: "Microsoft AI",
      elo: 1032,
      isCurrent: true,
      model: "MAI-Image-2.5-Flash",
      rank: 19,
    },
    {
      apiPricing: "$75.0 /1k imgs",
      creator: "Alibaba",
      elo: 1032,
      isCurrent: true,
      model: "Qwen Image 2.0 Pro (2026-04-22)",
      rank: 20,
    },
  ],
  source: "https://artificialanalysis.ai/image/leaderboard/text-to-image",
};

export const IMAGE_EDITING_TOP_20: LeaderboardSnapshot = {
  capturedAt: "2026-10-07",
  entries: [
    {
      apiPricing: "$210.7 /1k imgs",
      creator: "OpenAI",
      elo: 1183,
      isCurrent: true,
      model: "GPT Image 2.5 Sunburst (max)",
      rank: 1,
      routableModelId: "sunburst",
    },
    {
      apiPricing: "$210.7 /1k imgs",
      creator: "OpenAI",
      elo: 1163,
      isCurrent: true,
      model: "GPT Image 2.5 Flare (max)",
      rank: 2,
      routableModelId: "flare",
    },
    {
      apiPricing: "$38.9 /1k imgs",
      creator: "Microsoft AI",
      elo: 1139,
      isCurrent: true,
      model: "MAI-Image-2.6",
      rank: 3,
    },
    {
      apiPricing: "$19.5 /1k imgs",
      creator: "Microsoft AI",
      elo: 1127,
      isCurrent: true,
      model: "MAI-Image-2.6-Flash",
      rank: 4,
    },
    {
      apiPricing: "$211.0 /1k imgs",
      creator: "OpenAI",
      elo: 1125,
      isCurrent: true,
      model: "GPT Image 2 (high)",
      rank: 5,
      routableModelId: "gpt2",
    },
    {
      apiPricing: "$10.0 /1k imgs",
      creator: "Meta",
      elo: 1120,
      isCurrent: true,
      model: "Muse Image",
      rank: 6,
    },
    {
      apiPricing: "$48.1 /1k imgs",
      creator: "Microsoft AI",
      elo: 1114,
      isCurrent: true,
      model: "MAI-Image-2.5",
      rank: 7,
      routableModelId: "mai-image-2.5",
    },
    {
      apiPricing: "$60.0 /1k imgs",
      creator: "SpaceXAI",
      elo: 1110,
      isCurrent: true,
      model: "Grok Imagine Image 2.0",
      rank: 8,
      routableModelId: "grok-image-2",
    },
    {
      apiPricing: "$67.0 /1k imgs",
      creator: "Google",
      elo: 1110,
      isCurrent: true,
      model: "Nano Banana 2 (Gemini 3.1 Flash Image)",
      rank: 9,
      routableModelId: "banana2",
    },
    {
      apiPricing: "$108.5 /1k imgs",
      creator: "Microsoft AI",
      elo: 1110,
      isCurrent: true,
      model: "MAI-Image-2.5-Pro",
      rank: 10,
      routableModelId: "mai-image-2.5-pro",
    },
    {
      apiPricing: "$90.0 /1k imgs",
      creator: "ByteDance Seed",
      elo: 1108,
      isCurrent: true,
      model: "Seedream 5.0 Pro",
      rank: 11,
      routableModelId: "seedream5",
    },
    {
      apiPricing: "$133.0 /1k imgs",
      creator: "OpenAI",
      elo: 1103,
      isCurrent: true,
      model: "GPT Image 1.5 (high)",
      rank: 12,
      routableModelId: "gpt",
    },
    {
      apiPricing: "$134.0 /1k imgs",
      creator: "Google",
      elo: 1101,
      isCurrent: true,
      model: "Nano Banana Pro (Gemini 3 Pro Image)",
      rank: 13,
      routableModelId: "banana",
    },
    {
      apiPricing: "$20.0 /1k imgs",
      creator: "Microsoft AI",
      elo: 1089,
      isCurrent: true,
      model: "MAI-Image-2.5-Flash",
      rank: 14,
    },
    {
      apiPricing: "$24.0 /1k imgs",
      creator: "Tencent",
      elo: 1087,
      isCurrent: true,
      model: "HunyuanImage 3.5 (Preview)",
      rank: 15,
    },
    {
      apiPricing: "$50.0 /1k imgs",
      creator: "SpaceXAI",
      elo: 1086,
      isCurrent: true,
      model: "grok-imagine-image-quality",
      rank: 16,
    },
    {
      apiPricing: "$40.0 /1k imgs",
      creator: "Alibaba",
      elo: 1077,
      isCurrent: true,
      model: "Qwen-Image-3.0-Pro",
      rank: 17,
    },
    {
      apiPricing: "No API available",
      creator: "Alibaba",
      elo: 1074,
      isCurrent: true,
      model: "Qwen-Image-2.1",
      rank: 18,
    },
    {
      apiPricing: "$20.0 /1k imgs",
      creator: "SpaceXAI",
      elo: 1073,
      isCurrent: true,
      model: "grok-imagine-image",
      rank: 19,
      routableModelId: "grok-image",
    },
    {
      apiPricing: "$100.0 /1k imgs",
      creator: "Luma AI",
      elo: 1072,
      isCurrent: true,
      model: "Luma UNI 1 Max",
      rank: 20,
    },
  ],
  source: "https://artificialanalysis.ai/image/leaderboard/editing",
};

export const VIDEO_TEXT_TO_VIDEO_TOP_15: LeaderboardSnapshot = {
  capturedAt: "2026-05-12",
  entries: [
    {
      apiPricing: "$14.40/min",
      creator: "Alibaba-ATH",
      elo: 1354,
      model: "HappyHorse-1.0",
      rank: 1,
    },
    {
      apiPricing: "No API available",
      creator: "ByteDance Seed",
      elo: 1273,
      model: "Dreamina Seedance 2.0 720p",
      rank: 2,
    },
    {
      apiPricing: "$13.44/min",
      creator: "KlingAI",
      elo: 1249,
      model: "Kling 3.0 1080p (Pro)",
      rank: 3,
    },
    {
      apiPricing: "$13.44/min",
      creator: "KlingAI",
      elo: 1233,
      model: "Kling 3.0 Omni 1080p (Pro)",
      rank: 4,
    },
    {
      apiPricing: "$4.20/min",
      creator: "xAI",
      elo: 1233,
      model: "grok-imagine-video",
      rank: 5,
    },
    {
      apiPricing: "$9.60/min",
      creator: "Vidu",
      elo: 1225,
      model: "Vidu Q3 Pro",
      rank: 6,
    },
    {
      apiPricing: "$3.00/min",
      creator: "Video Rebirth",
      elo: 1224,
      model: "Bach-1.0 Preview",
      rank: 7,
    },
    {
      apiPricing: "$10.08/min",
      creator: "KlingAI",
      elo: 1224,
      model: "Kling 3.0 Omni 720p (Standard)",
      rank: 8,
    },
    {
      apiPricing: "$5.40/min",
      creator: "PixVerse",
      elo: 1222,
      model: "PixVerse V6",
      rank: 9,
    },
    {
      apiPricing: "$9.00/min",
      creator: "PixVerse",
      elo: 1221,
      model: "PixVerse V5.6",
      rank: 10,
    },
    {
      apiPricing: "No API available",
      creator: "Runway",
      elo: 1220,
      model: "Runway Gen-4.5",
      rank: 11,
    },
    {
      apiPricing: "$12.00/min",
      creator: "Google",
      elo: 1218,
      model: "Veo 3",
      rank: 12,
    },
    {
      apiPricing: "$10.08/min",
      creator: "KlingAI",
      elo: 1215,
      model: "Kling 3.0 720p (Standard)",
      rank: 13,
    },
    {
      apiPricing: "$3.00/min",
      creator: "Google",
      elo: 1214,
      model: "Veo 3.1 Lite",
      rank: 14,
    },
    {
      apiPricing: "$10.08/min",
      creator: "KlingAI",
      elo: 1209,
      model: "Kling O1 Pro (January)",
      rank: 15,
    },
  ],
  source: "https://artificialanalysis.ai/video/leaderboard/text-to-video",
};

export const VIDEO_IMAGE_TO_VIDEO_TOP_15: LeaderboardSnapshot = {
  capturedAt: "2026-05-12",
  entries: [
    {
      apiPricing: "Coming soon",
      creator: "Alibaba-ATH",
      elo: 1395,
      model: "HappyHorse-1.0",
      rank: 1,
    },
    {
      apiPricing: "No API available",
      creator: "ByteDance Seed",
      elo: 1348,
      model: "Dreamina Seedance 2.0 720p",
      rank: 2,
    },
    {
      apiPricing: "$4.20/min",
      creator: "xAI",
      elo: 1326,
      model: "grok-imagine-video",
      rank: 3,
    },
    {
      apiPricing: "$5.40/min",
      creator: "PixVerse",
      elo: 1322,
      model: "PixVerse V6",
      rank: 4,
    },
    {
      apiPricing: "$9.60/min",
      creator: "Vidu",
      elo: 1287,
      model: "Vidu Q3 Pro",
      rank: 5,
    },
    {
      apiPricing: "$4.20/min",
      creator: "KlingAI",
      elo: 1283,
      model: "Kling 2.5 Turbo 1080p",
      rank: 6,
    },
    {
      apiPricing: "$13.44/min",
      creator: "KlingAI",
      elo: 1280,
      model: "Kling 3.0 1080p (Pro)",
      rank: 7,
    },
    {
      apiPricing: "$9.00/min",
      creator: "PixVerse",
      elo: 1279,
      model: "PixVerse V5.6",
      rank: 8,
    },
    {
      apiPricing: "$13.44/min",
      creator: "KlingAI",
      elo: 1277,
      model: "Kling 3.0 Omni 1080p (Pro)",
      rank: 9,
    },
    {
      apiPricing: "Coming soon",
      creator: "KlingAI",
      elo: 1271,
      model: "Kling 2.6 Standard (January)",
      rank: 10,
    },
    {
      apiPricing: "$6.40/min",
      creator: "PixVerse",
      elo: 1271,
      model: "PixVerse V5.5",
      rank: 11,
    },
    {
      apiPricing: "$6.00/min",
      creator: "Google",
      elo: 1268,
      model: "Veo 3.1 Fast",
      rank: 12,
    },
    {
      apiPricing: "No API available",
      creator: "Runway",
      elo: 1263,
      model: "Runway Gen-4.5",
      rank: 13,
    },
    {
      apiPricing: "$10.08/min",
      creator: "KlingAI",
      elo: 1263,
      model: "Kling 3.0 Omni 720p (Standard)",
      rank: 14,
    },
    {
      apiPricing: "$10.08/min",
      creator: "KlingAI",
      elo: 1263,
      model: "Kling 3.0 720p (Standard)",
      rank: 15,
    },
  ],
  source: "https://artificialanalysis.ai/video/leaderboard/image-to-video",
};
