export interface LeaderboardEntry {
  apiPricing?: string;
  creator: string;
  elo: number;
  isCurrent?: boolean;
  model: string;
  rank: number;
  routableModelId?: string;
}

export interface LeaderboardSnapshot {
  capturedAt: string;
  entries: LeaderboardEntry[];
  source: string;
}

export const IMAGE_TEXT_TO_IMAGE_TOP_20: LeaderboardSnapshot = {
  capturedAt: "2026-08-23",
  entries: [
    {
      apiPricing: "$211/1k images",
      creator: "OpenAI",
      elo: 1369,
      isCurrent: true,
      model: "GPT Image 2 (high)",
      rank: 1,
      routableModelId: "gpt2",
    },
    {
      apiPricing: "$200/1k images",
      creator: "Reve",
      elo: 1322,
      isCurrent: true,
      model: "Reve 2.1",
      rank: 2,
      routableModelId: "reve",
    },
    {
      apiPricing: "$67/1k images",
      creator: "Google",
      elo: 1320,
      isCurrent: true,
      model: "Nano Banana 2 (Gemini 3.1 Flash Image Preview)",
      rank: 3,
      routableModelId: "banana2",
    },
    {
      apiPricing: "$133/1k images",
      creator: "OpenAI",
      elo: 1310,
      isCurrent: true,
      model: "GPT Image 1.5 (high)",
      rank: 4,
      routableModelId: "gpt",
    },
    {
      apiPricing: "$48/1k images",
      creator: "Microsoft AI",
      elo: 1305,
      isCurrent: true,
      model: "MAI-Image-2.5",
      rank: 5,
    },
    {
      apiPricing: "$134/1k images",
      creator: "Google",
      elo: 1297,
      isCurrent: true,
      model: "Nano Banana Pro (Gemini 3 Pro Image)",
      rank: 6,
      routableModelId: "banana",
    },
    {
      apiPricing: "$109/1k images",
      creator: "Microsoft AI",
      elo: 1293,
      isCurrent: true,
      model: "MAI-Image-2.5-Pro",
      rank: 7,
    },
    {
      apiPricing: "$34/1k images",
      creator: "Google",
      elo: 1289,
      isCurrent: true,
      model: "Nano Banana 2 Lite (Gemini 3.1 Flash Lite Image)",
      rank: 8,
    },
    {
      apiPricing: "$43/1k images",
      creator: "Alibaba",
      elo: 1282,
      isCurrent: true,
      model: "Qwen-Image-3.0-Pro",
      rank: 9,
    },
    {
      apiPricing: "$90/1k images",
      creator: "Bytedance",
      elo: 1279,
      isCurrent: true,
      model: "Seedream 5.0 Pro",
      rank: 10,
      routableModelId: "seedream5",
    },
    {
      apiPricing: "$30/1k images",
      creator: "Alibaba",
      elo: 1272,
      isCurrent: true,
      model: "Qwen-Image-3.0",
      rank: 11,
      routableModelId: "qwen3",
    },
    {
      apiPricing: "$75/1k images",
      creator: "Alibaba",
      elo: 1237,
      isCurrent: true,
      model: "Qwen Image 2.0 Pro",
      rank: 12,
    },
    {
      apiPricing: "$50/1k images",
      creator: "SpaceXAI",
      elo: 1234,
      isCurrent: true,
      model: "grok-imagine-image-quality",
      rank: 13,
    },
    {
      apiPricing: "$20/1k images",
      creator: "Microsoft AI",
      elo: 1228,
      isCurrent: true,
      model: "MAI-Image-2.5-Flash",
      rank: 14,
    },
    {
      apiPricing: "$80/1k images",
      creator: "HiDream",
      elo: 1228,
      isCurrent: true,
      model: "HiDream-O1-Image-1.5",
      rank: 15,
    },
    {
      apiPricing: "$30/1k images",
      creator: "ByteDance Seed",
      elo: 1226,
      isCurrent: true,
      model: "Seedream 4.0",
      rank: 16,
      routableModelId: "seedream4",
    },
    {
      apiPricing: "$70/1k images",
      creator: "Black Forest Labs",
      elo: 1225,
      isCurrent: true,
      model: "FLUX.2 [max]",
      rank: 17,
      routableModelId: "flux2-max",
    },
    {
      apiPricing: "$60/1k images",
      creator: "Black Forest Labs",
      elo: 1223,
      isCurrent: true,
      model: "FLUX.2 [flex]",
      rank: 18,
      routableModelId: "flux2-flex",
    },
    {
      apiPricing: "$60/1k images",
      creator: "Ideogram",
      elo: 1220,
      isCurrent: true,
      model: "Ideogram 4.0",
      rank: 19,
      routableModelId: "ideogram4",
    },
    {
      apiPricing: "$60/1k images",
      creator: "Krea",
      elo: 1220,
      isCurrent: true,
      model: "Krea 2 Large",
      rank: 20,
    },
  ],
  source: "https://artificialanalysis.ai/image/leaderboard/text-to-image",
};

export const IMAGE_EDITING_TOP_20: LeaderboardSnapshot = {
  capturedAt: "2026-08-23",
  entries: [
    {
      apiPricing: "$109/1k images",
      creator: "Microsoft AI",
      elo: 1272,
      isCurrent: true,
      model: "MAI-Image-2.5-Pro",
      rank: 1,
    },
    {
      apiPricing: "$200/1k images",
      creator: "Reve",
      elo: 1263,
      isCurrent: true,
      model: "Reve 2.1",
      rank: 2,
      routableModelId: "reve",
    },
    {
      apiPricing: "$211/1k images",
      creator: "OpenAI",
      elo: 1256,
      isCurrent: true,
      model: "GPT Image 2 (high)",
      rank: 3,
      routableModelId: "gpt2",
    },
    {
      apiPricing: "$48/1k images",
      creator: "Microsoft AI",
      elo: 1256,
      isCurrent: true,
      model: "MAI-Image-2.5",
      rank: 4,
    },
    {
      apiPricing: "$133/1k images",
      creator: "OpenAI",
      elo: 1250,
      isCurrent: true,
      model: "GPT Image 1.5 (high)",
      rank: 5,
      routableModelId: "gpt",
    },
    {
      apiPricing: "$43/1k images",
      creator: "Alibaba",
      elo: 1250,
      isCurrent: true,
      model: "Qwen-Image-3.0-Pro",
      rank: 6,
    },
    {
      apiPricing: "$67/1k images",
      creator: "Google",
      elo: 1249,
      isCurrent: true,
      model: "Nano Banana 2 (Gemini 3.1 Flash Image Preview)",
      rank: 7,
      routableModelId: "banana2",
    },
    {
      apiPricing: "$90/1k images",
      creator: "Bytedance",
      elo: 1248,
      isCurrent: true,
      model: "Seedream 5.0 Pro",
      rank: 8,
      routableModelId: "seedream5",
    },
    {
      apiPricing: "$134/1k images",
      creator: "Google",
      elo: 1245,
      isCurrent: true,
      model: "Nano Banana Pro (Gemini 3 Pro Image)",
      rank: 9,
      routableModelId: "banana",
    },
    {
      apiPricing: "$20/1k images",
      creator: "Microsoft AI",
      elo: 1236,
      isCurrent: true,
      model: "MAI-Image-2.5-Flash",
      rank: 10,
    },
    {
      apiPricing: "$50/1k images",
      creator: "SpaceXAI",
      elo: 1226,
      isCurrent: true,
      model: "grok-imagine-image-quality",
      rank: 11,
    },
    {
      apiPricing: "$90/1k images",
      creator: "Tencent",
      elo: 1222,
      isCurrent: true,
      model: "HunyuanImage 3.0 Instruct",
      rank: 12,
    },
    {
      apiPricing: "$80/1k images",
      creator: "Newport AI",
      elo: 1220,
      isCurrent: true,
      model: "DreamImage 2.0",
      rank: 13,
    },
    {
      apiPricing: "$100/1k images",
      creator: "Luma Labs",
      elo: 1219,
      isCurrent: true,
      model: "Luma UNI 1 Max",
      rank: 14,
    },
    {
      apiPricing: "$33/1k images",
      creator: "Alibaba",
      elo: 1218,
      isCurrent: true,
      model: "Qwen-Image-3.0",
      rank: 15,
      routableModelId: "qwen3",
    },
    {
      apiPricing: "$20/1k images",
      creator: "SpaceXAI",
      elo: 1214,
      isCurrent: true,
      model: "grok-imagine-image",
      rank: 16,
      routableModelId: "grok-image",
    },
    {
      apiPricing: "$28/1k images",
      creator: "KlingAI",
      elo: 1208,
      isCurrent: true,
      model: "Kling Image 3.0 Omni",
      rank: 17,
    },
    {
      apiPricing: "$34/1k images",
      creator: "Google",
      elo: 1202,
      isCurrent: true,
      model: "Nano Banana 2 Lite",
      rank: 18,
    },
    {
      apiPricing: "$140/1k images",
      creator: "Black Forest Labs",
      elo: 1201,
      isCurrent: true,
      model: "FLUX.2 [max]",
      rank: 19,
      routableModelId: "flux2-max",
    },
    {
      creator: "Alibaba",
      elo: 1200,
      isCurrent: true,
      model: "Wan 2.7 Pro",
      rank: 20,
    },
  ],
  source: "https://artificialanalysis.ai/image/leaderboard/editing",
};

export const VIDEO_TEXT_TO_VIDEO_TOP_15: LeaderboardSnapshot = {
  capturedAt: "2026-05-12",
  entries: [
    {
      apiPricing: "$14.40/min",
      creator: "Alibaba-ATH",
      elo: 1354,
      model: "HappyHorse-1.0",
      rank: 1,
    },
    {
      apiPricing: "No API available",
      creator: "ByteDance Seed",
      elo: 1273,
      model: "Dreamina Seedance 2.0 720p",
      rank: 2,
    },
    {
      apiPricing: "$13.44/min",
      creator: "KlingAI",
      elo: 1249,
      model: "Kling 3.0 1080p (Pro)",
      rank: 3,
    },
    {
      apiPricing: "$13.44/min",
      creator: "KlingAI",
      elo: 1233,
      model: "Kling 3.0 Omni 1080p (Pro)",
      rank: 4,
    },
    {
      apiPricing: "$4.20/min",
      creator: "xAI",
      elo: 1233,
      model: "grok-imagine-video",
      rank: 5,
    },
    {
      apiPricing: "$9.60/min",
      creator: "Vidu",
      elo: 1225,
      model: "Vidu Q3 Pro",
      rank: 6,
    },
    {
      apiPricing: "$3.00/min",
      creator: "Video Rebirth",
      elo: 1224,
      model: "Bach-1.0 Preview",
      rank: 7,
    },
    {
      apiPricing: "$10.08/min",
      creator: "KlingAI",
      elo: 1224,
      model: "Kling 3.0 Omni 720p (Standard)",
      rank: 8,
    },
    {
      apiPricing: "$5.40/min",
      creator: "PixVerse",
      elo: 1222,
      model: "PixVerse V6",
      rank: 9,
    },
    {
      apiPricing: "$9.00/min",
      creator: "PixVerse",
      elo: 1221,
      model: "PixVerse V5.6",
      rank: 10,
    },
    {
      apiPricing: "No API available",
      creator: "Runway",
      elo: 1220,
      model: "Runway Gen-4.5",
      rank: 11,
    },
    {
      apiPricing: "$12.00/min",
      creator: "Google",
      elo: 1218,
      model: "Veo 3",
      rank: 12,
    },
    {
      apiPricing: "$10.08/min",
      creator: "KlingAI",
      elo: 1215,
      model: "Kling 3.0 720p (Standard)",
      rank: 13,
    },
    {
      apiPricing: "$3.00/min",
      creator: "Google",
      elo: 1214,
      model: "Veo 3.1 Lite",
      rank: 14,
    },
    {
      apiPricing: "$10.08/min",
      creator: "KlingAI",
      elo: 1209,
      model: "Kling O1 Pro (January)",
      rank: 15,
    },
  ],
  source: "https://artificialanalysis.ai/video/leaderboard/text-to-video",
};

export const VIDEO_IMAGE_TO_VIDEO_TOP_15: LeaderboardSnapshot = {
  capturedAt: "2026-05-12",
  entries: [
    {
      apiPricing: "Coming soon",
      creator: "Alibaba-ATH",
      elo: 1395,
      model: "HappyHorse-1.0",
      rank: 1,
    },
    {
      apiPricing: "No API available",
      creator: "ByteDance Seed",
      elo: 1348,
      model: "Dreamina Seedance 2.0 720p",
      rank: 2,
    },
    {
      apiPricing: "$4.20/min",
      creator: "xAI",
      elo: 1326,
      model: "grok-imagine-video",
      rank: 3,
    },
    {
      apiPricing: "$5.40/min",
      creator: "PixVerse",
      elo: 1322,
      model: "PixVerse V6",
      rank: 4,
    },
    {
      apiPricing: "$9.60/min",
      creator: "Vidu",
      elo: 1287,
      model: "Vidu Q3 Pro",
      rank: 5,
    },
    {
      apiPricing: "$4.20/min",
      creator: "KlingAI",
      elo: 1283,
      model: "Kling 2.5 Turbo 1080p",
      rank: 6,
    },
    {
      apiPricing: "$13.44/min",
      creator: "KlingAI",
      elo: 1280,
      model: "Kling 3.0 1080p (Pro)",
      rank: 7,
    },
    {
      apiPricing: "$9.00/min",
      creator: "PixVerse",
      elo: 1279,
      model: "PixVerse V5.6",
      rank: 8,
    },
    {
      apiPricing: "$13.44/min",
      creator: "KlingAI",
      elo: 1277,
      model: "Kling 3.0 Omni 1080p (Pro)",
      rank: 9,
    },
    {
      apiPricing: "Coming soon",
      creator: "KlingAI",
      elo: 1271,
      model: "Kling 2.6 Standard (January)",
      rank: 10,
    },
    {
      apiPricing: "$6.40/min",
      creator: "PixVerse",
      elo: 1271,
      model: "PixVerse V5.5",
      rank: 11,
    },
    {
      apiPricing: "$6.00/min",
      creator: "Google",
      elo: 1268,
      model: "Veo 3.1 Fast",
      rank: 12,
    },
    {
      apiPricing: "No API available",
      creator: "Runway",
      elo: 1263,
      model: "Runway Gen-4.5",
      rank: 13,
    },
    {
      apiPricing: "$10.08/min",
      creator: "KlingAI",
      elo: 1263,
      model: "Kling 3.0 Omni 720p (Standard)",
      rank: 14,
    },
    {
      apiPricing: "$10.08/min",
      creator: "KlingAI",
      elo: 1263,
      model: "Kling 3.0 720p (Standard)",
      rank: 15,
    },
  ],
  source: "https://artificialanalysis.ai/video/leaderboard/image-to-video",
};
