/* oxlint-disable sonarjs/no-duplicate-string -- this file is hand-curated
 * public leaderboard data (creator names, model names, pricing strings) —
 * each entry below is independently sourced from Artificial Analysis and
 * updated on its own cadence, so extracting the incidentally-repeated
 * values (e.g. "Black Forest Labs" appearing across several rank entries)
 * into shared constants would add indirection without reducing real
 * duplication of *logic*. The one genuinely shared value, the snapshot
 * date, is already factored out as LEADERBOARD_SNAPSHOT_DATE below.
 */

export interface LeaderboardEntry {
  apiPricing?: string;
  creator: string;
  elo: number;
  isCurrent?: boolean;
  model: string;
  rank: number;
  routableModelId?: string;
}

export interface LeaderboardSnapshot {
  capturedAt: string;
  entries: LeaderboardEntry[];
  source: string;
}

const LEADERBOARD_SNAPSHOT_DATE = "2026-05-12";

export const IMAGE_TEXT_TO_IMAGE_TOP_20: LeaderboardSnapshot = {
  capturedAt: LEADERBOARD_SNAPSHOT_DATE,
  entries: [
    {
      apiPricing: "$211/1k images",
      creator: "OpenAI",
      elo: 1337,
      isCurrent: true,
      model: "GPT Image 2 (high)",
      rank: 1,
      routableModelId: "gpt2",
    },
    {
      apiPricing: "$133/1k images",
      creator: "OpenAI",
      elo: 1268,
      isCurrent: true,
      model: "GPT Image 1.5 (high)",
      rank: 2,
      routableModelId: "gpt",
    },
    {
      apiPricing: "$67/1k images",
      creator: "Google",
      elo: 1263,
      isCurrent: true,
      model: "Nano Banana 2 (Gemini 3.1 Flash Image Preview)",
      rank: 3,
      routableModelId: "banana2",
    },
    {
      apiPricing: "$150/1k images",
      creator: "Sourceful",
      elo: 1256,
      isCurrent: true,
      model: "Riverflow 2.0",
      rank: 4,
    },
    {
      apiPricing: "$134/1k images",
      creator: "Google",
      elo: 1220,
      isCurrent: true,
      model: "Nano Banana Pro (Gemini 3 Pro Image)",
      rank: 5,
      routableModelId: "banana",
    },
    {
      apiPricing: "$30/1k images",
      creator: "ByteDance Seed",
      elo: 1198,
      isCurrent: true,
      model: "Seedream 4.0",
      rank: 6,
      routableModelId: "seedream4",
    },
    {
      apiPricing: "$50/1k images",
      creator: "Microsoft",
      elo: 1198,
      isCurrent: true,
      model: "MAI-Image-2",
      rank: 7,
    },
    {
      apiPricing: "$70/1k images",
      creator: "Black Forest Labs",
      elo: 1197,
      isCurrent: true,
      model: "FLUX.2 [max]",
      rank: 8,
      routableModelId: "flux2-max",
    },
    {
      apiPricing: "Unavailable",
      creator: "Peanut",
      elo: 1187,
      isCurrent: true,
      model: "Peanut (Open Weights Coming Soon)",
      rank: 9,
    },
    {
      apiPricing: "$30/1k images",
      creator: "Black Forest Labs",
      elo: 1186,
      isCurrent: true,
      model: "FLUX.2 [pro]",
      rank: 10,
      routableModelId: "flux2-pro",
    },
    {
      apiPricing: "$60/1k images",
      creator: "Google",
      elo: 1184,
      isCurrent: false,
      model: "Imagen 4 Ultra Preview 0606",
      rank: 11,
    },
    {
      apiPricing: "$20/1k images",
      creator: "xAI",
      elo: 1182,
      isCurrent: true,
      model: "grok-imagine-image",
      rank: 12,
      routableModelId: "grok-image",
    },
    {
      apiPricing: "$60/1k images",
      creator: "Black Forest Labs",
      elo: 1182,
      isCurrent: true,
      model: "FLUX.2 [flex]",
      rank: 13,
      routableModelId: "flux2-flex",
    },
    {
      apiPricing: "$30/1k images",
      creator: "ImagineArt",
      elo: 1181,
      isCurrent: true,
      model: "ImagineArt 2.0",
      rank: 14,
    },
    {
      apiPricing: "$60/1k images",
      creator: "Google",
      elo: 1171,
      isCurrent: true,
      model: "Imagen 4 Ultra",
      rank: 15,
    },
    {
      apiPricing: "$40/1k images",
      creator: "Google",
      elo: 1169,
      isCurrent: false,
      model: "Imagen 4 Preview 0606",
      rank: 16,
    },
    {
      apiPricing: "$40/1k images",
      creator: "ByteDance Seed",
      elo: 1167,
      isCurrent: true,
      model: "Seedream 4.5",
      rank: 17,
      routableModelId: "seedream45",
    },
    {
      apiPricing: "$8/1k images",
      creator: "Fal",
      elo: 1161,
      isCurrent: true,
      model: "FLUX.2 [dev] Turbo",
      rank: 18,
    },
    {
      apiPricing: "$12/1k images",
      creator: "Black Forest Labs",
      elo: 1160,
      isCurrent: true,
      model: "FLUX.2 [dev]",
      rank: 19,
      routableModelId: "flux2-dev",
    },
    {
      apiPricing: "$20/1k images",
      creator: "Alibaba",
      elo: 1158,
      isCurrent: true,
      model: "Qwen Image Max 2512",
      rank: 20,
      routableModelId: "qwen",
    },
  ],
  source: "https://artificialanalysis.ai/image/leaderboard/text-to-image",
};

export const IMAGE_EDITING_TOP_20: LeaderboardSnapshot = {
  capturedAt: LEADERBOARD_SNAPSHOT_DATE,
  entries: [
    {
      apiPricing: "$150/1k images",
      creator: "Sourceful",
      elo: 1286,
      isCurrent: true,
      model: "Riverflow 2.0",
      rank: 1,
    },
    {
      apiPricing: "$133/1k images",
      creator: "OpenAI",
      elo: 1262,
      isCurrent: true,
      model: "GPT Image 1.5 (high)",
      rank: 2,
      routableModelId: "gpt",
    },
    {
      apiPricing: "$211/1k images",
      creator: "OpenAI",
      elo: 1249,
      isCurrent: true,
      model: "GPT Image 2 (high)",
      rank: 3,
      routableModelId: "gpt2",
    },
    {
      apiPricing: "$134/1k images",
      creator: "Google",
      elo: 1241,
      isCurrent: true,
      model: "Nano Banana Pro (Gemini 3 Pro Image)",
      rank: 4,
      routableModelId: "banana",
    },
    {
      apiPricing: "$67/1k images",
      creator: "Google",
      elo: 1231,
      isCurrent: true,
      model: "Nano Banana 2 (Gemini 3.1 Flash Image Preview)",
      rank: 5,
      routableModelId: "banana2",
    },
    {
      apiPricing: "$90/1k images",
      creator: "Tencent",
      elo: 1222,
      isCurrent: true,
      model: "HunyuanImage 3.0 Instruct (Fal)",
      rank: 6,
    },
    {
      apiPricing: "$20/1k images",
      creator: "xAI",
      elo: 1213,
      isCurrent: true,
      model: "grok-imagine-image",
      rank: 7,
      routableModelId: "grok-image",
    },
    {
      apiPricing: "$70/1k images",
      creator: "xAI",
      elo: 1212,
      isCurrent: true,
      model: "grok-imagine-image-pro",
      rank: 8,
    },
    {
      apiPricing: "Unavailable",
      creator: "KlingAI",
      elo: 1207,
      isCurrent: true,
      model: "Kling Image 3.0 Omni",
      rank: 9,
    },
    {
      apiPricing: "$140/1k images",
      creator: "Black Forest Labs",
      elo: 1206,
      isCurrent: true,
      model: "FLUX.2 [max]",
      rank: 10,
      routableModelId: "flux2-max",
    },
    {
      apiPricing: "Unavailable",
      creator: "Alibaba",
      elo: 1200,
      isCurrent: true,
      model: "Wan 2.7 Pro",
      rank: 11,
    },
    {
      apiPricing: "$28/1k images",
      creator: "KlingAI",
      elo: 1196,
      isCurrent: true,
      model: "Kling Image 3.0",
      rank: 12,
    },
    {
      apiPricing: "$28/1k images",
      creator: "KlingAI",
      elo: 1193,
      isCurrent: true,
      model: "Kling Image O1",
      rank: 13,
    },
    {
      apiPricing: "$30/1k images",
      creator: "Alibaba",
      elo: 1188,
      isCurrent: true,
      model: "Wan 2.6 Image",
      rank: 14,
    },
    {
      apiPricing: "$66/1k images",
      creator: "Sourceful",
      elo: 1184,
      isCurrent: true,
      model: "Riverflow 1",
      rank: 15,
    },
    {
      apiPricing: "$30/1k images",
      creator: "ByteDance Seed",
      elo: 1184,
      isCurrent: true,
      model: "Seedream 4.0",
      rank: 16,
      routableModelId: "seedream4",
    },
    {
      apiPricing: "$40/1k images",
      creator: "ByteDance Seed",
      elo: 1184,
      isCurrent: true,
      model: "Seedream 4.5",
      rank: 17,
      routableModelId: "seedream45",
    },
    {
      apiPricing: "$26/1k images",
      creator: "Alibaba",
      elo: 1181,
      isCurrent: true,
      model: "Wan 2.7",
      rank: 18,
    },
    {
      apiPricing: "$39/1k images",
      creator: "Google",
      elo: 1173,
      isCurrent: true,
      model: "Nano Banana (Gemini 2.5 Flash Image)",
      rank: 19,
      routableModelId: "gemini",
    },
    {
      apiPricing: "$40/1k images",
      creator: "Reve",
      elo: 1172,
      isCurrent: true,
      model: "Reve V1 (December)",
      rank: 20,
    },
  ],
  source: "https://artificialanalysis.ai/image/leaderboard/editing",
};

export const VIDEO_TEXT_TO_VIDEO_TOP_15: LeaderboardSnapshot = {
  capturedAt: LEADERBOARD_SNAPSHOT_DATE,
  entries: [
    {
      apiPricing: "$14.40/min",
      creator: "Alibaba-ATH",
      elo: 1354,
      model: "HappyHorse-1.0",
      rank: 1,
    },
    {
      apiPricing: "No API available",
      creator: "ByteDance Seed",
      elo: 1273,
      model: "Dreamina Seedance 2.0 720p",
      rank: 2,
    },
    {
      apiPricing: "$13.44/min",
      creator: "KlingAI",
      elo: 1249,
      model: "Kling 3.0 1080p (Pro)",
      rank: 3,
    },
    {
      apiPricing: "$13.44/min",
      creator: "KlingAI",
      elo: 1233,
      model: "Kling 3.0 Omni 1080p (Pro)",
      rank: 4,
    },
    {
      apiPricing: "$4.20/min",
      creator: "xAI",
      elo: 1233,
      model: "grok-imagine-video",
      rank: 5,
    },
    {
      apiPricing: "$9.60/min",
      creator: "Vidu",
      elo: 1225,
      model: "Vidu Q3 Pro",
      rank: 6,
    },
    {
      apiPricing: "$3.00/min",
      creator: "Video Rebirth",
      elo: 1224,
      model: "Bach-1.0 Preview",
      rank: 7,
    },
    {
      apiPricing: "$10.08/min",
      creator: "KlingAI",
      elo: 1224,
      model: "Kling 3.0 Omni 720p (Standard)",
      rank: 8,
    },
    {
      apiPricing: "$5.40/min",
      creator: "PixVerse",
      elo: 1222,
      model: "PixVerse V6",
      rank: 9,
    },
    {
      apiPricing: "$9.00/min",
      creator: "PixVerse",
      elo: 1221,
      model: "PixVerse V5.6",
      rank: 10,
    },
    {
      apiPricing: "No API available",
      creator: "Runway",
      elo: 1220,
      model: "Runway Gen-4.5",
      rank: 11,
    },
    {
      apiPricing: "$12.00/min",
      creator: "Google",
      elo: 1218,
      model: "Veo 3",
      rank: 12,
    },
    {
      apiPricing: "$10.08/min",
      creator: "KlingAI",
      elo: 1215,
      model: "Kling 3.0 720p (Standard)",
      rank: 13,
    },
    {
      apiPricing: "$3.00/min",
      creator: "Google",
      elo: 1214,
      model: "Veo 3.1 Lite",
      rank: 14,
    },
    {
      apiPricing: "$10.08/min",
      creator: "KlingAI",
      elo: 1209,
      model: "Kling O1 Pro (January)",
      rank: 15,
    },
  ],
  source: "https://artificialanalysis.ai/video/leaderboard/text-to-video",
};

export const VIDEO_IMAGE_TO_VIDEO_TOP_15: LeaderboardSnapshot = {
  capturedAt: LEADERBOARD_SNAPSHOT_DATE,
  entries: [
    {
      apiPricing: "Coming soon",
      creator: "Alibaba-ATH",
      elo: 1395,
      model: "HappyHorse-1.0",
      rank: 1,
    },
    {
      apiPricing: "No API available",
      creator: "ByteDance Seed",
      elo: 1348,
      model: "Dreamina Seedance 2.0 720p",
      rank: 2,
    },
    {
      apiPricing: "$4.20/min",
      creator: "xAI",
      elo: 1326,
      model: "grok-imagine-video",
      rank: 3,
    },
    {
      apiPricing: "$5.40/min",
      creator: "PixVerse",
      elo: 1322,
      model: "PixVerse V6",
      rank: 4,
    },
    {
      apiPricing: "$9.60/min",
      creator: "Vidu",
      elo: 1287,
      model: "Vidu Q3 Pro",
      rank: 5,
    },
    {
      apiPricing: "$4.20/min",
      creator: "KlingAI",
      elo: 1283,
      model: "Kling 2.5 Turbo 1080p",
      rank: 6,
    },
    {
      apiPricing: "$13.44/min",
      creator: "KlingAI",
      elo: 1280,
      model: "Kling 3.0 1080p (Pro)",
      rank: 7,
    },
    {
      apiPricing: "$9.00/min",
      creator: "PixVerse",
      elo: 1279,
      model: "PixVerse V5.6",
      rank: 8,
    },
    {
      apiPricing: "$13.44/min",
      creator: "KlingAI",
      elo: 1277,
      model: "Kling 3.0 Omni 1080p (Pro)",
      rank: 9,
    },
    {
      apiPricing: "Coming soon",
      creator: "KlingAI",
      elo: 1271,
      model: "Kling 2.6 Standard (January)",
      rank: 10,
    },
    {
      apiPricing: "$6.40/min",
      creator: "PixVerse",
      elo: 1271,
      model: "PixVerse V5.5",
      rank: 11,
    },
    {
      apiPricing: "$6.00/min",
      creator: "Google",
      elo: 1268,
      model: "Veo 3.1 Fast",
      rank: 12,
    },
    {
      apiPricing: "No API available",
      creator: "Runway",
      elo: 1263,
      model: "Runway Gen-4.5",
      rank: 13,
    },
    {
      apiPricing: "$10.08/min",
      creator: "KlingAI",
      elo: 1263,
      model: "Kling 3.0 Omni 720p (Standard)",
      rank: 14,
    },
    {
      apiPricing: "$10.08/min",
      creator: "KlingAI",
      elo: 1263,
      model: "Kling 3.0 720p (Standard)",
      rank: 15,
    },
  ],
  source: "https://artificialanalysis.ai/video/leaderboard/image-to-video",
};
