import type { ModelConfig } from "./types";

const AA_IMAGE_LEADERBOARD_SNAPSHOT = "2026-08-23";
const AA_IMAGE_SOURCES = [
  "https://artificialanalysis.ai/image/leaderboard/text-to-image",
  "https://artificialanalysis.ai/image/leaderboard/editing",
];
const FAL_PRICING_CHECKED_AT = "2026-05-12";
// July 2026 tier-1 additions (MOT-18): verified against fal model pages.
const FAL_PRICING_CHECKED_JUL_2026 = "2026-07-11";
const FAL_PRICING_CHECKED_AUG_2026 = "2026-08-23";

export const MODELS: Record<string, ModelConfig> = {
  // ─── Generation Models ────────────────────────────────────────

  gpt2: {
    benchmark: {
      artificialAnalysis: {
        editing: { elo: 1256, pricePer1k: 211, rank: 3 },
        snapshotDate: AA_IMAGE_LEADERBOARD_SNAPSHOT,
        sourceUrls: AA_IMAGE_SOURCES,
        textToImage: { elo: 1369, pricePer1k: 211, rank: 1 },
      },
      speed: {
        medianSeconds: 200.7,
        p95Seconds: 232.6,
        source: "artificial-analysis-models",
      },
      tiers: { price: "ultra", quality: "frontier", speed: "very_slow" },
      useCase: "Highest-ranked text-to-image quality and transparent PNGs",
    },
    editEndpoint: "openai/gpt-image-2/image-to-image",
    endpoint: "openai/gpt-image-2",
    falPricing: {
      checkedAt: FAL_PRICING_CHECKED_AT,
      currency: "USD",
      endpointId: "openai/gpt-image-2",
      estimatedCostPerImageUsd: 0.211,
      source: "fal-pricing-api",
      unit: "units",
      unitPrice: 1,
    },
    maxReferenceImages: 4,
    name: "GPT Image 2",
    pricePerImageUsd: 0.211,
    pricing: "$0.211",
    sizeMode: "image_size_enum",
    supportsAspect: true,
    supportsEdit: true,
    supportsMaskImage: true,
    supportsNumImages: true,
    supportsOutputFormat: true,
    supportsQuality: true,
    supportsResolution: false,
    supportsSyncMode: true,
    type: "generation",
    useQueue: true,
  },
  gpt: {
    benchmark: {
      artificialAnalysis: {
        editing: { elo: 1250, pricePer1k: 133, rank: 5 },
        snapshotDate: AA_IMAGE_LEADERBOARD_SNAPSHOT,
        sourceUrls: AA_IMAGE_SOURCES,
        textToImage: { elo: 1310, pricePer1k: 133, rank: 4 },
      },
      speed: {
        medianSeconds: 34.6,
        p95Seconds: 38.3,
        source: "artificial-analysis-models",
      },
      tiers: { price: "ultra", quality: "frontier", speed: "slow" },
      useCase: "Best OpenAI edit quality with transparent PNG support",
    },
    editEndpoint: "fal-ai/gpt-image-1.5/edit",
    endpoint: "fal-ai/gpt-image-1.5",
    falPricing: {
      checkedAt: FAL_PRICING_CHECKED_AT,
      currency: "USD",
      endpointId: "fal-ai/gpt-image-1.5",
      estimatedCostPerImageUsd: 0.133,
      source: "fal-pricing-api",
      unit: "units",
      unitPrice: 1,
    },
    maxReferenceImages: 4,
    name: "GPT Image 1.5",
    pricePerImageUsd: 0.133,
    pricing: "$0.133",
    sizeMode: "gpt_size",
    supportsAspect: false,
    supportsBackground: true,
    supportsEdit: true,
    supportsMaskImage: true,
    supportsNumImages: true,
    supportsOutputFormat: true,
    supportsQuality: true,
    supportsResolution: false,
    supportsSyncMode: true,
    type: "generation",
  },
  banana2: {
    benchmark: {
      artificialAnalysis: {
        editing: { elo: 1249, pricePer1k: 67, rank: 7 },
        snapshotDate: AA_IMAGE_LEADERBOARD_SNAPSHOT,
        sourceUrls: AA_IMAGE_SOURCES,
        textToImage: { elo: 1320, pricePer1k: 67, rank: 3 },
      },
      tiers: { price: "premium", quality: "frontier", speed: "unknown" },
      useCase: "Best balance of quality, edit support, web search, and cost",
    },
    editEndpoint: "fal-ai/nano-banana-2/edit",
    endpoint: "fal-ai/nano-banana-2",
    falPricing: {
      checkedAt: FAL_PRICING_CHECKED_AT,
      currency: "USD",
      endpointId: "fal-ai/nano-banana-2",
      estimatedCostPerImageUsd: 0.08,
      source: "fal-pricing-api",
      unit: "images",
      unitPrice: 0.08,
    },
    maxReferenceImages: 4,
    name: "Nano Banana 2",
    pricePerImageUsd: 0.08,
    pricing: "$0.08",
    sizeMode: "aspect_ratio",
    supportsAspect: true,
    supportsEdit: true,
    supportsGoogleSearch: true,
    supportsLimitGenerations: true,
    supportsNumImages: true,
    supportsOutputFormat: true,
    supportsResolution: true,
    supportsSafetyTolerance: true,
    supportsSeed: true,
    supportsSyncMode: true,
    supportsThinkingLevel: true,
    supportsWebSearch: true,
    type: "generation",
  },
  banana: {
    benchmark: {
      artificialAnalysis: {
        editing: { elo: 1245, pricePer1k: 134, rank: 9 },
        snapshotDate: AA_IMAGE_LEADERBOARD_SNAPSHOT,
        sourceUrls: AA_IMAGE_SOURCES,
        textToImage: { elo: 1297, pricePer1k: 134, rank: 6 },
      },
      speed: {
        medianSeconds: 19.2,
        p95Seconds: 30.3,
        source: "artificial-analysis-models",
      },
      tiers: { price: "ultra", quality: "frontier", speed: "balanced" },
      useCase: "Premium Gemini image generation and multi-reference edits",
    },
    editEndpoint: "fal-ai/nano-banana-pro/edit",
    endpoint: "fal-ai/nano-banana-pro",
    falPricing: {
      checkedAt: FAL_PRICING_CHECKED_AT,
      currency: "USD",
      endpointId: "fal-ai/nano-banana-pro",
      estimatedCostPerImageUsd: 0.15,
      source: "fal-pricing-api",
      unit: "images",
      unitPrice: 0.15,
    },
    maxReferenceImages: 14,
    name: "Nano Banana Pro",
    pricePerImageUsd: 0.15,
    pricing: "$0.15",
    sizeMode: "aspect_ratio",
    supportsAspect: true,
    supportsEdit: true,
    supportsGoogleSearch: true,
    supportsLimitGenerations: true,
    supportsNumImages: true,
    supportsOutputFormat: true,
    supportsResolution: true,
    supportsSafetyTolerance: true,
    supportsSeed: true,
    supportsSyncMode: true,
    supportsWebSearch: true,
    type: "generation",
  },
  gemini: {
    benchmark: {
      artificialAnalysis: {
        editing: { elo: 1180, pricePer1k: 39, rank: 29 },
        snapshotDate: AA_IMAGE_LEADERBOARD_SNAPSHOT,
        sourceUrls: AA_IMAGE_SOURCES,
      },
    },
    editEndpoint: "fal-ai/gemini-25-flash-image/edit",
    endpoint: "fal-ai/gemini-25-flash-image",
    falPricing: {
      checkedAt: FAL_PRICING_CHECKED_AT,
      currency: "USD",
      endpointId: "fal-ai/gemini-25-flash-image",
      estimatedCostPerImageUsd: 0.0398,
      source: "fal-pricing-api",
      unit: "images",
      unitPrice: 0.0398,
    },
    maxReferenceImages: 4,
    name: "Gemini 2.5 Flash",
    pricePerImageUsd: 0.0398,
    pricing: "$0.04",
    sizeMode: "aspect_ratio",
    supportsAspect: true,
    supportsEdit: true,
    supportsNumImages: true,
    supportsOutputFormat: true,
    supportsResolution: false,
    supportsSafetyTolerance: true,
    supportsSeed: true,
    supportsSyncMode: true,
    type: "generation",
  },
  gemini3: {
    benchmark: {
      artificialAnalysis: {
        editing: { elo: 1245, pricePer1k: 134, rank: 9 },
        snapshotDate: AA_IMAGE_LEADERBOARD_SNAPSHOT,
        sourceUrls: AA_IMAGE_SOURCES,
        textToImage: { elo: 1297, pricePer1k: 134, rank: 6 },
      },
    },
    editEndpoint: "fal-ai/gemini-3-pro-image-preview/edit",
    endpoint: "fal-ai/gemini-3-pro-image-preview",
    falPricing: {
      checkedAt: FAL_PRICING_CHECKED_AT,
      currency: "USD",
      endpointId: "fal-ai/gemini-3-pro-image-preview",
      estimatedCostPerImageUsd: 0.15,
      source: "fal-pricing-api",
      unit: "images",
      unitPrice: 0.15,
    },
    maxReferenceImages: 4,
    name: "Gemini 3 Pro",
    pricePerImageUsd: 0.15,
    pricing: "$0.15",
    sizeMode: "aspect_ratio",
    supportsAspect: true,
    supportsEdit: true,
    supportsNumImages: true,
    supportsOutputFormat: true,
    supportsResolution: true,
    supportsSafetyTolerance: true,
    supportsSeed: true,
    supportsSyncMode: true,
    supportsWebSearch: true,
    type: "generation",
  },
  seedream4: {
    benchmark: {
      artificialAnalysis: {
        editing: { elo: 1185, pricePer1k: 30, rank: 28 },
        snapshotDate: AA_IMAGE_LEADERBOARD_SNAPSHOT,
        sourceUrls: AA_IMAGE_SOURCES,
        textToImage: { elo: 1226, pricePer1k: 30, rank: 16 },
      },
      speed: {
        medianSeconds: 14.3,
        p95Seconds: 21,
        source: "artificial-analysis-models",
      },
      tiers: { price: "budget", quality: "best", speed: "balanced" },
      useCase: "High-ranked budget generation and large multi-reference edits",
    },
    editEndpoint: "fal-ai/bytedance/seedream/v4/edit",
    endpoint: "fal-ai/bytedance/seedream/v4/text-to-image",
    falPricing: {
      checkedAt: FAL_PRICING_CHECKED_AT,
      currency: "USD",
      endpointId: "fal-ai/bytedance/seedream/v4/text-to-image",
      estimatedCostPerImageUsd: 0.03,
      source: "fal-pricing-api",
      unit: "images",
      unitPrice: 0.03,
    },
    maxReferenceImages: 10,
    name: "Seedream 4.0",
    pricePerImageUsd: 0.03,
    pricing: "$0.03",
    sizeMode: "image_size_enum",
    supportsAspect: true,
    supportsEdit: true,
    supportsNumImages: true,
    supportsResolution: false,
    supportsSeed: true,
    supportsSyncMode: true,
    type: "generation",
  },
  seedream45: {
    benchmark: {
      artificialAnalysis: {
        editing: { elo: 1186, pricePer1k: 40, rank: 26 },
        snapshotDate: AA_IMAGE_LEADERBOARD_SNAPSHOT,
        sourceUrls: AA_IMAGE_SOURCES,
        textToImage: { elo: 1203, pricePer1k: 40, rank: 32 },
      },
      speed: {
        medianSeconds: 18.2,
        p95Seconds: 43.3,
        source: "artificial-analysis-models",
      },
      tiers: { price: "standard", quality: "better", speed: "balanced" },
      useCase: "Cheap current Seedream model with good animation/art scores",
    },
    editEndpoint: "fal-ai/bytedance/seedream/v4.5/edit",
    endpoint: "fal-ai/bytedance/seedream/v4.5/text-to-image",
    falPricing: {
      checkedAt: FAL_PRICING_CHECKED_AT,
      currency: "USD",
      endpointId: "fal-ai/bytedance/seedream/v4.5/text-to-image",
      estimatedCostPerImageUsd: 0.04,
      source: "fal-pricing-api",
      unit: "images",
      unitPrice: 0.04,
    },
    maxReferenceImages: 10,
    name: "Seedream 4.5",
    pricePerImageUsd: 0.04,
    pricing: "$0.04",
    sizeMode: "image_size_enum",
    supportsAspect: true,
    supportsEdit: true,
    supportsNumImages: true,
    supportsResolution: false,
    supportsSeed: true,
    supportsSyncMode: true,
    type: "generation",
  },
  seedream5: {
    benchmark: {
      artificialAnalysis: {
        editing: { elo: 1248, pricePer1k: 90, rank: 8 },
        snapshotDate: AA_IMAGE_LEADERBOARD_SNAPSHOT,
        sourceUrls: AA_IMAGE_SOURCES,
        textToImage: { elo: 1279, pricePer1k: 90, rank: 10 },
      },
    },
    name: "Seedream 5.0 Pro",
    endpoint: "bytedance/seedream/v5/pro/text-to-image",
    editEndpoint: "bytedance/seedream/v5/pro/edit",
    type: "generation",
    // fal tiers Seedream v5 Pro by output size: $0.0675 up to 1536², $0.135 up to 2048².
    pricing: "$0.0675 (≤1536²) / $0.135 (≤2048²)",
    pricePerImageUsd: 0.0675,
    falPricing: {
      checkedAt: FAL_PRICING_CHECKED_JUL_2026,
      currency: "USD",
      endpointId: "bytedance/seedream/v5/pro/text-to-image",
      estimatedCostPerImageUsd: 0.0675,
      source: "fal-pricing-api",
      unit: "images",
      unitPrice: 0.0675,
    },
    sizeMode: "image_size_enum",
    supportsAspect: true,
    supportsResolution: false,
    supportsEdit: true,
    supportsNumImages: true,
    supportsSeed: true,
    supportsSyncMode: true,
    maxReferenceImages: 10,
  },
  "seedream5-lite": {
    benchmark: {
      artificialAnalysis: {
        editing: { elo: 1169, pricePer1k: 35, rank: 32 },
        snapshotDate: AA_IMAGE_LEADERBOARD_SNAPSHOT,
        sourceUrls: AA_IMAGE_SOURCES,
      },
    },
    name: "Seedream 5.0 Lite",
    endpoint: "fal-ai/bytedance/seedream/v5/lite/text-to-image",
    editEndpoint: "fal-ai/bytedance/seedream/v5/lite/edit",
    type: "generation",
    // Flat price regardless of resolution; native up to Auto 3K (~9.4MP).
    pricing: "$0.035",
    pricePerImageUsd: 0.035,
    falPricing: {
      checkedAt: FAL_PRICING_CHECKED_JUL_2026,
      currency: "USD",
      endpointId: "fal-ai/bytedance/seedream/v5/lite/text-to-image",
      estimatedCostPerImageUsd: 0.035,
      source: "fal-pricing-api",
      unit: "images",
      unitPrice: 0.035,
    },
    sizeMode: "image_size_enum",
    supportsAspect: true,
    supportsResolution: false,
    supportsEdit: true,
    supportsNumImages: true,
    supportsSeed: true,
    supportsSyncMode: true,
    maxReferenceImages: 10,
  },
  "flux2-max": {
    benchmark: {
      artificialAnalysis: {
        editing: { elo: 1201, pricePer1k: 140, rank: 19 },
        snapshotDate: AA_IMAGE_LEADERBOARD_SNAPSHOT,
        sourceUrls: AA_IMAGE_SOURCES,
        textToImage: { elo: 1225, pricePer1k: 70, rank: 17 },
      },
      speed: {
        medianSeconds: 31.6,
        p95Seconds: 41,
        source: "artificial-analysis-models",
      },
      tiers: { price: "premium", quality: "best", speed: "slow" },
      useCase: "Best FLUX quality and high-end editing",
    },
    editEndpoint: "fal-ai/flux-2-max/edit",
    endpoint: "fal-ai/flux-2-max",
    falPricing: {
      checkedAt: FAL_PRICING_CHECKED_AT,
      currency: "USD",
      endpointId: "fal-ai/flux-2-max",
      estimatedCostPerImageUsd: 0.07,
      source: "fal-pricing-api",
      unit: "megapixels",
      unitPrice: 0.07,
    },
    maxReferenceImages: 10,
    name: "FLUX.2 Max",
    pricePerImageUsd: 0.07,
    pricing: "$0.07/MP",
    sizeMode: "image_size_enum",
    supportsAspect: true,
    supportsEdit: true,
    supportsNumImages: false,
    supportsOutputFormat: true,
    supportsResolution: false,
    supportsSafetyChecker: true,
    supportsSafetyTolerance: true,
    supportsSeed: true,
    supportsSyncMode: true,
    type: "generation",
  },
  "flux2-pro": {
    benchmark: {
      artificialAnalysis: {
        editing: { elo: 1170, pricePer1k: 45, rank: 31 },
        snapshotDate: AA_IMAGE_LEADERBOARD_SNAPSHOT,
        sourceUrls: AA_IMAGE_SOURCES,
        textToImage: { elo: 1207, pricePer1k: 30, rank: 30 },
      },
      speed: {
        medianSeconds: 16.1,
        p95Seconds: 23.9,
        source: "artificial-analysis-models",
      },
      tiers: { price: "budget", quality: "best", speed: "balanced" },
      useCase: "Production FLUX quality at a low per-megapixel price",
    },
    editEndpoint: "fal-ai/flux-2-pro/edit",
    endpoint: "fal-ai/flux-2-pro",
    falPricing: {
      checkedAt: FAL_PRICING_CHECKED_AT,
      currency: "USD",
      endpointId: "fal-ai/flux-2-pro",
      estimatedCostPerImageUsd: 0.03,
      source: "fal-pricing-api",
      unit: "processed megapixels",
      unitPrice: 0.03,
    },
    maxReferenceImages: 10,
    name: "FLUX.2 Pro",
    pricePerImageUsd: 0.03,
    pricing: "$0.03/MP",
    sizeMode: "image_size_enum",
    supportsAspect: true,
    supportsEdit: true,
    supportsNumImages: false,
    supportsOutputFormat: true,
    supportsResolution: false,
    supportsSafetyChecker: true,
    supportsSafetyTolerance: true,
    supportsSeed: true,
    supportsSyncMode: true,
    type: "generation",
  },
  "flux2-flex": {
    benchmark: {
      artificialAnalysis: {
        snapshotDate: AA_IMAGE_LEADERBOARD_SNAPSHOT,
        sourceUrls: AA_IMAGE_SOURCES,
        textToImage: { elo: 1223, pricePer1k: 60, rank: 18 },
      },
      speed: {
        medianSeconds: 15.3,
        p95Seconds: 22.2,
        source: "artificial-analysis-models",
      },
      tiers: { price: "standard", quality: "best", speed: "balanced" },
      useCase: "FLUX quality with guidance and step controls",
    },
    editEndpoint: "fal-ai/flux-2-flex/edit",
    endpoint: "fal-ai/flux-2-flex",
    falPricing: {
      checkedAt: FAL_PRICING_CHECKED_AT,
      currency: "USD",
      endpointId: "fal-ai/flux-2-flex",
      estimatedCostPerImageUsd: 0.05,
      source: "fal-pricing-api",
      unit: "processed megapixels",
      unitPrice: 0.05,
    },
    maxReferenceImages: 10,
    name: "FLUX.2 Flex",
    pricePerImageUsd: 0.05,
    pricing: "$0.05/MP",
    sizeMode: "image_size_enum",
    supportedOutputFormats: ["jpeg", "png"],
    supportsAspect: true,
    supportsEdit: true,
    supportsGuidanceScale: true,
    supportsInferenceSteps: true,
    supportsNumImages: false,
    supportsOutputFormat: true,
    supportsResolution: false,
    supportsSafetyChecker: true,
    supportsSafetyTolerance: true,
    supportsSeed: true,
    supportsSyncMode: true,
    type: "generation",
  },
  "flux2-dev": {
    benchmark: {
      artificialAnalysis: {
        snapshotDate: AA_IMAGE_LEADERBOARD_SNAPSHOT,
        sourceUrls: AA_IMAGE_SOURCES,
      },
      speed: {
        medianSeconds: 4.6,
        p95Seconds: 69.6,
        source: "artificial-analysis-models",
      },
      tiers: { price: "variable", quality: "better", speed: "fast" },
      useCase: "Open FLUX.2 quality with low average cost",
    },
    editEndpoint: "fal-ai/flux-2/edit",
    endpoint: "fal-ai/flux-2",
    falPricing: {
      checkedAt: FAL_PRICING_CHECKED_AT,
      currency: "USD",
      endpointId: "fal-ai/flux-2",
      estimatedCostPerImageUsd: 0.012,
      source: "fal-pricing-api",
      unit: "compute seconds",
      unitPrice: 0.00167,
    },
    maxReferenceImages: 10,
    name: "FLUX.2 [dev]",
    pricePerImageUsd: 0.012,
    pricing: "$0.00167/sec",
    sizeMode: "image_size_enum",
    supportsAspect: true,
    supportsEdit: true,
    supportsGuidanceScale: true,
    supportsInferenceSteps: true,
    supportsNumImages: true,
    supportsOutputFormat: true,
    supportsResolution: false,
    supportsSafetyChecker: true,
    supportsSafetyTolerance: true,
    supportsSeed: true,
    supportsSyncMode: true,
    type: "generation",
  },
  "flux2-turbo": {
    endpoint: "fal-ai/flux-2/turbo",
    falPricing: {
      checkedAt: FAL_PRICING_CHECKED_JUL_2026,
      currency: "USD",
      endpointId: "fal-ai/flux-2/turbo",
      estimatedCostPerImageUsd: 0.008,
      source: "fal-pricing-api",
      unit: "megapixels",
      unitPrice: 0.008,
    },
    name: "FLUX.2 Turbo",
    pricePerImageUsd: 0.008,
    pricing: "$0.008/MP",
    sizeMode: "image_size_enum",
    supportsAspect: true,
    supportsEdit: false,
    supportsGuidanceScale: true,
    supportsNumImages: true,
    supportsOutputFormat: true,
    supportsResolution: false,
    supportsSafetyChecker: true,
    supportsSeed: true,
    supportsSyncMode: true,
    type: "generation",
  },
  flux: {
    endpoint: "fal-ai/flux-pro/v1.1-ultra",
    falPricing: {
      checkedAt: FAL_PRICING_CHECKED_AT,
      currency: "USD",
      endpointId: "fal-ai/flux-pro/v1.1-ultra",
      estimatedCostPerImageUsd: 0.06,
      source: "fal-pricing-api",
      unit: "images",
      unitPrice: 0.06,
    },
    maxReferenceImages: 1,
    name: "FLUX Pro Ultra",
    pricePerImageUsd: 0.06,
    pricing: "$0.06",
    sizeMode: "aspect_ratio",
    supportsAspect: true,
    supportsEdit: true,
    supportsEnhancePrompt: true,
    supportsImagePromptStrength: true,
    supportsNumImages: true,
    supportsOutputFormat: true,
    supportsRaw: true,
    supportsResolution: false,
    supportsSafetyTolerance: true,
    supportsSeed: true,
    supportsSyncMode: true,
    type: "generation",
  },
  "flux-fast": {
    endpoint: "fal-ai/flux/schnell",
    falPricing: {
      checkedAt: FAL_PRICING_CHECKED_AT,
      currency: "USD",
      endpointId: "fal-ai/flux/schnell",
      estimatedCostPerImageUsd: 0.003,
      source: "fal-pricing-api",
      unit: "megapixels",
      unitPrice: 0.003,
    },
    name: "FLUX Schnell",
    pricePerImageUsd: 0.003,
    pricing: "$0.003",
    sizeMode: "image_size_enum",
    supportsAspect: true,
    supportsEdit: false,
    supportsGuidanceScale: true,
    supportsInferenceSteps: true,
    supportsNumImages: true,
    supportsOutputFormat: true,
    supportsResolution: false,
    supportsSeed: true,
    supportsSyncMode: true,
    type: "generation",
  },
  recraft: {
    endpoint: "fal-ai/recraft-v3",
    falPricing: {
      checkedAt: FAL_PRICING_CHECKED_AT,
      currency: "USD",
      endpointId: "fal-ai/recraft-v3",
      estimatedCostPerImageUsd: 0.04,
      source: "fal-pricing-api",
      unit: "images",
      unitPrice: 0.04,
    },
    name: "Recraft V3",
    pricePerImageUsd: 0.04,
    pricing: "$0.04",
    sizeMode: "image_size_enum",
    supportsAspect: true,
    supportsEdit: false,
    supportsNumImages: false,
    supportsResolution: false,
    supportsStyle: true,
    supportsSyncMode: true,
    type: "generation",
  },
  reve: {
    benchmark: {
      artificialAnalysis: {
        // #2 on BOTH boards, which almost nothing else manages - the top text-to-image model
        // (GPT Image 2) drops to 3rd for editing, and the top editor (MAI-Image-2.5-Pro) is not
        // on fal at all. Reve is the best editor motif can actually reach.
        editing: { elo: 1263, pricePer1k: 200, rank: 2 },
        snapshotDate: AA_IMAGE_LEADERBOARD_SNAPSHOT,
        sourceUrls: AA_IMAGE_SOURCES,
        textToImage: { elo: 1322, pricePer1k: 200, rank: 2 },
      },
      tiers: { price: "premium", quality: "frontier", speed: "unknown" },
      useCase:
        "Highest-ranked editor reachable on fal; strong prompt adherence and text rendering",
    },
    editEndpoint: "fal-ai/reve/edit",
    endpoint: "fal-ai/reve/text-to-image",
    falPricing: {
      checkedAt: FAL_PRICING_CHECKED_AUG_2026,
      currency: "USD",
      endpointId: "fal-ai/reve/text-to-image",
      estimatedCostPerImageUsd: 0.04,
      source: "fal-pricing-api",
      unit: "images",
      unitPrice: 0.04,
    },
    maxReferenceImages: 1,
    name: "Reve 2.1",
    pricePerImageUsd: 0.04,
    pricing: "$0.04",
    // fal's schema takes aspect_ratio from a fixed set and has no width/height or resolution
    // parameter, so aspect is supported and resolution is not.
    sizeMode: "aspect_ratio",
    supportsAspect: true,
    supportsEdit: true,
    supportsNumImages: true,
    supportsOutputFormat: true,
    supportsResolution: false,
    supportsSeed: false,
    supportsSyncMode: true,
    type: "generation",
  },
  recraft4: {
    benchmark: {
      artificialAnalysis: {
        snapshotDate: AA_IMAGE_LEADERBOARD_SNAPSHOT,
        sourceUrls: AA_IMAGE_SOURCES,
        textToImage: { elo: 1215, pricePer1k: 35, rank: 25 },
      },
    },
    endpoint: "fal-ai/recraft/v4/text-to-image",
    falPricing: {
      checkedAt: FAL_PRICING_CHECKED_JUL_2026,
      currency: "USD",
      endpointId: "fal-ai/recraft/v4/text-to-image",
      estimatedCostPerImageUsd: 0.04,
      source: "fal-pricing-api",
      unit: "images",
      unitPrice: 0.04,
    },
    name: "Recraft V4",
    pricePerImageUsd: 0.04,
    pricing: "$0.04",
    sizeMode: "image_size_enum",
    supportsAspect: true,
    supportsEdit: false,
    supportsNumImages: false,
    supportsResolution: false,
    supportsStyle: true,
    supportsSyncMode: true,
    type: "generation",
  },
  ideogram: {
    endpoint: "fal-ai/ideogram/v3",
    falPricing: {
      checkedAt: FAL_PRICING_CHECKED_AT,
      currency: "USD",
      endpointId: "fal-ai/ideogram/v3",
      estimatedCostPerImageUsd: 0.03,
      source: "fal-pricing-api",
      unit: "images",
      unitPrice: 0.03,
    },
    name: "Ideogram V3",
    pricePerImageUsd: 0.03,
    pricing: "$0.03",
    sizeMode: "image_size_enum",
    supportsAspect: true,
    supportsEdit: false,
    supportsExpandPrompt: true,
    supportsNegativePrompt: true,
    supportsNumImages: true,
    supportsRenderingSpeed: true,
    supportsResolution: false,
    supportsSeed: true,
    supportsStyle: true,
    supportsSyncMode: true,
    type: "generation",
  },
  ideogram4: {
    benchmark: {
      artificialAnalysis: {
        snapshotDate: AA_IMAGE_LEADERBOARD_SNAPSHOT,
        sourceUrls: AA_IMAGE_SOURCES,
        textToImage: { elo: 1220, pricePer1k: 60, rank: 19 },
      },
    },
    name: "Ideogram V4",
    endpoint: "ideogram/v4",
    type: "generation",
    // fal bills v4 per output megapixel by rendering speed: TURBO $0.03, BALANCED
    // $0.06, QUALITY $0.10 (plus a flat $0.03 when prompt expansion is used).
    // Headline uses the TURBO 1MP rate, matching how ideogram v3 is modeled.
    pricing: "$0.03",
    pricePerImageUsd: 0.03,
    falPricing: {
      checkedAt: FAL_PRICING_CHECKED_JUL_2026,
      currency: "USD",
      endpointId: "ideogram/v4",
      estimatedCostPerImageUsd: 0.03,
      source: "fal-pricing-api",
      unit: "megapixels",
      unitPrice: 0.03,
    },
    sizeMode: "image_size_enum",
    supportsAspect: true,
    supportsResolution: false,
    supportsEdit: false,
    supportsNumImages: true,
    supportsRenderingSpeed: true,
    supportsSeed: true,
    supportsOutputFormat: true,
    supportedOutputFormats: ["jpeg", "png"],
    supportsSafetyChecker: true,
    supportsSyncMode: true,
  },
  "grok-image": {
    benchmark: {
      artificialAnalysis: {
        editing: { elo: 1214, pricePer1k: 20, rank: 16 },
        snapshotDate: AA_IMAGE_LEADERBOARD_SNAPSHOT,
        sourceUrls: AA_IMAGE_SOURCES,
        textToImage: { elo: 1216, pricePer1k: 20, rank: 23 },
      },
      speed: {
        medianSeconds: 5.1,
        p95Seconds: 6.5,
        source: "artificial-analysis-models",
      },
      tiers: { price: "budget", quality: "best", speed: "fast" },
      useCase: "Very fast, cheap generation and edits",
    },
    editEndpoint: "xai/grok-imagine-image/edit",
    endpoint: "xai/grok-imagine-image",
    falPricing: {
      checkedAt: FAL_PRICING_CHECKED_AT,
      currency: "USD",
      endpointId: "xai/grok-imagine-image",
      estimatedCostPerImageUsd: 0.02,
      source: "fal-pricing-api",
      unit: "images",
      unitPrice: 0.02,
    },
    maxReferenceImages: 4,
    name: "Grok Imagine Image",
    pricePerImageUsd: 0.02,
    pricing: "$0.02",
    sizeMode: "aspect_ratio",
    supportsAspect: true,
    supportsEdit: true,
    supportsNumImages: true,
    supportsOutputFormat: true,
    supportsResolution: true,
    supportsSyncMode: true,
    type: "generation",
  },
  qwen: {
    benchmark: {
      artificialAnalysis: {
        snapshotDate: AA_IMAGE_LEADERBOARD_SNAPSHOT,
        sourceUrls: AA_IMAGE_SOURCES,
      },
      speed: {
        medianSeconds: 23.3,
        p95Seconds: 491,
        source: "artificial-analysis-models",
      },
      tiers: { price: "budget", quality: "better", speed: "slow" },
      useCase: "Low-cost open-weight text and design generation",
    },
    endpoint: "fal-ai/qwen-image",
    falPricing: {
      checkedAt: FAL_PRICING_CHECKED_AT,
      currency: "USD",
      endpointId: "fal-ai/qwen-image",
      estimatedCostPerImageUsd: 0.02,
      source: "fal-pricing-api",
      unit: "megapixels",
      unitPrice: 0.02,
    },
    name: "Qwen Image",
    pricePerImageUsd: 0.02,
    pricing: "$0.02/MP",
    sizeMode: "image_size_enum",
    supportsAspect: true,
    supportsEdit: false,
    supportsNumImages: true,
    supportsOutputFormat: true,
    supportsResolution: false,
    supportsSeed: true,
    supportsSyncMode: true,
    type: "generation",
  },
  qwen3: {
    benchmark: {
      artificialAnalysis: {
        editing: { elo: 1218, pricePer1k: 33, rank: 15 },
        snapshotDate: AA_IMAGE_LEADERBOARD_SNAPSHOT,
        sourceUrls: AA_IMAGE_SOURCES,
        textToImage: { elo: 1272, pricePer1k: 30, rank: 11 },
      },
      tiers: { price: "budget", quality: "better", speed: "unknown" },
      useCase: "Strong quality per dollar - 11th on text-to-image at $30/1k",
    },
    endpoint: "fal-ai/qwen-image-3/text-to-image",
    falPricing: {
      checkedAt: "2026-08-05",
      currency: "USD",
      endpointId: "fal-ai/qwen-image-3/text-to-image",
      estimatedCostPerImageUsd: 0.02,
      source: "fal-pricing-api",
      unit: "megapixels",
      unitPrice: 0.02,
    },
    name: "Qwen Image 3",
    pricePerImageUsd: 0.02,
    pricing:
      "$0.02/MP (assumed from qwen v1; fal pricing page bot-gated at check time)",
    sizeMode: "image_size_enum",
    supportsAspect: true,
    supportsEdit: false,
    supportsNegativePrompt: true,
    supportsNumImages: true,
    supportsOutputFormat: true,
    supportsResolution: false,
    supportsSafetyChecker: true,
    supportsSeed: true,
    type: "generation",
  },

  // ─── Video Models ─────────────────────────────────────────────

  kling: {
    endpoint: "fal-ai/kling-video/v3/pro/image-to-video",
    name: "Kling v3 Pro",
    pricing: "$0.11/sec",
    sizeMode: "none",
    supportsAspect: false,
    supportsEdit: false,
    supportsNumImages: false,
    supportsResolution: false,
    type: "video",
  },

  // ─── Utility Models ───────────────────────────────────────────

  clarity: {
    endpoint: "fal-ai/clarity-upscaler",
    name: "Clarity Upscaler",
    pricing: "$0.03/MP",
    supportsAspect: false,
    supportsEdit: false,
    supportsNumImages: false,
    supportsResolution: false,
    type: "utility",
  },
  crystal: {
    endpoint: "clarityai/crystal-upscaler",
    name: "Crystal Upscaler",
    pricing: "$0.02",
    supportsAspect: false,
    supportsEdit: false,
    supportsNumImages: false,
    supportsResolution: false,
    type: "utility",
  },
  rmbg: {
    endpoint: "fal-ai/birefnet",
    name: "BiRefNet (Background Removal)",
    pricing: "$0.02",
    supportsAspect: false,
    supportsEdit: false,
    supportsNumImages: false,
    supportsResolution: false,
    type: "utility",
  },
  bria: {
    endpoint: "fal-ai/bria/background/remove",
    name: "Bria RMBG 2.0",
    pricing: "$0.02",
    supportsAspect: false,
    supportsEdit: false,
    supportsNumImages: false,
    supportsResolution: false,
    type: "utility",
  },
};

export const GENERATION_MODELS = [
  "gpt2",
  "gpt",
  "banana2",
  "banana",
  "gemini",
  "gemini3",
  "seedream4",
  "seedream45",
  "seedream5",
  "seedream5-lite",
  "flux2-max",
  "flux2-pro",
  "flux2-flex",
  "flux2-dev",
  "flux2-turbo",
  "flux",
  "flux-fast",
  "recraft",
  "recraft4",
  "ideogram",
  "ideogram4",
  "grok-image",
  "qwen",
  "qwen3",
] as const;

/** Models whose fal endpoints support image editing (vary/edit flows). */
export const EDIT_CAPABLE_MODELS = GENERATION_MODELS.filter(
  (id) => MODELS[id]?.supportsEdit === true
);

export const UTILITY_MODELS = ["clarity", "crystal", "rmbg", "bria"] as const;

export const VIDEO_MODELS = ["kling"] as const;

export type GenerationModelName = (typeof GENERATION_MODELS)[number];

/** Recraft v3 style presets. Pass as the `style` field in GenerateOptions. */
export const RECRAFT_STYLES = [
  // Realistic
  "realistic_image",
  "realistic_image/b_and_w",
  "realistic_image/enterprise",
  "realistic_image/hard_flash",
  "realistic_image/hdr",
  "realistic_image/motion_blur",
  "realistic_image/natural_light",
  "realistic_image/studio_portrait",
  "realistic_image/long_exposure",
  // Digital illustration
  "digital_illustration",
  "digital_illustration/2d_art_poster",
  "digital_illustration/2d_art_poster_2",
  "digital_illustration/engraving_color",
  "digital_illustration/grain",
  "digital_illustration/hand_drawn",
  "digital_illustration/hand_drawn_outline",
  "digital_illustration/handmade_3d",
  "digital_illustration/infantile_sketch",
  "digital_illustration/pixel_art",
  "digital_illustration/psychedelic",
  "digital_illustration/seamless",
  "digital_illustration/voxel",
  "digital_illustration/watercolor",
  // Vector illustration
  "vector_illustration",
  "vector_illustration/cartoon",
  "vector_illustration/doodle_line_art",
  "vector_illustration/engraving",
  "vector_illustration/flat_2",
  "vector_illustration/kawaii",
  "vector_illustration/line_art",
  "vector_illustration/line_circuit",
  "vector_illustration/linocut",
  "vector_illustration/zentangle",
] as const;

/** Ideogram v3 top-level style categories. Pass as the `style` field in GenerateOptions. */
export const IDEOGRAM_STYLES = [
  "AUTO",
  "GENERAL",
  "REALISTIC",
  "DESIGN",
] as const;
