import type { ModelConfig } from "./types";

const AA_IMAGE_LEADERBOARD_SNAPSHOT = "2026-08-23";
const AA_IMAGE_SOURCES = [
  "https://artificialanalysis.ai/image/leaderboard/text-to-image",
  "https://artificialanalysis.ai/image/leaderboard/editing",
];
const FAL_PRICING_CHECKED_AT = "2026-05-12";
// July 2026 tier-1 additions (MOT-18): verified against fal model pages.
const FAL_PRICING_CHECKED_JUL_2026 = "2026-07-11";
const FAL_PRICING_CHECKED_AUG_2026 = "2026-08-23";
// MOT-59 additions and endpoint moves: verified against fal model pages and OpenAPI.
const FAL_PRICING_CHECKED_SEP_2026 = "2026-09-16";

export const MODELS: Record<string, ModelConfig> = {
  // ─── Generation Models ────────────────────────────────────────

  flare: {
    customImageSize: {
      maxEdge: 3840,
      maxPixels: 8_294_400,
      maxRatio: 3,
      minPixels: 655_360,
      multipleOf: 16,
    },
    editEndpoint: "openai/gpt-image-2.5/flare/edit",
    endpoint: "openai/gpt-image-2.5/flare/text-to-image",
    maxReferenceImages: 16,
    name: "GPT Image 2.5 Flare",
    pricing:
      "Token-based: text $5/M input, $1.25/M cached, $10/M output; image $8/M input, $2/M cached, $30/M output",
    pricePerImageUsd: null,
    sizeMode: "image_size_enum",
    supportsAspect: true,
    supportsBackground: true,
    supportsEdit: true,
    supportsMaskImage: true,
    maskImageField: "mask_url",
    supportsNumImages: true,
    supportsOutputFormat: true,
    supportsQuality: true,
    supportedQualities: ["auto", "low", "medium", "high", "xhigh", "max"],
    supportsResolution: false,
    supportsSyncMode: true,
    type: "generation",
    useQueue: true,
  },
  sunburst: {
    customImageSize: {
      maxEdge: 3840,
      maxPixels: 8_294_400,
      maxRatio: 3,
      minPixels: 655_360,
      multipleOf: 16,
    },
    editEndpoint: "openai/gpt-image-2.5/sunburst/edit",
    endpoint: "openai/gpt-image-2.5/sunburst/text-to-image",
    maxReferenceImages: 16,
    name: "GPT Image 2.5 Sunburst",
    pricing:
      "Token-based: text $5/M input, $1.25/M cached, $10/M output; image $8/M input, $2/M cached, $30/M output",
    pricePerImageUsd: null,
    sizeMode: "image_size_enum",
    supportsAspect: true,
    supportsBackground: true,
    supportsEdit: true,
    supportsMaskImage: true,
    maskImageField: "mask_url",
    supportsNumImages: true,
    supportsOutputFormat: true,
    supportsQuality: true,
    supportedQualities: ["auto", "low", "medium", "high", "xhigh", "max"],
    supportsResolution: false,
    supportsSyncMode: true,
    type: "generation",
    useQueue: true,
  },
  gpt2: {
    benchmark: {
      artificialAnalysis: {
        editing: { elo: 1256, rank: 3 },
        snapshotDate: AA_IMAGE_LEADERBOARD_SNAPSHOT,
        sourceUrls: AA_IMAGE_SOURCES,
        textToImage: { elo: 1369, rank: 1 },
      },
      speed: {
        medianSeconds: 200.7,
        p95Seconds: 232.6,
        source: "artificial-analysis-models",
      },
      tiers: { price: "ultra", quality: "frontier", speed: "very_slow" },
      useCase: "Highest-ranked text-to-image quality and transparent PNGs",
    },
    customImageSize: {
      maxEdge: 3840,
      maxPixels: 8_294_400,
      maxRatio: 3,
      minPixels: 655_360,
      multipleOf: 16,
    },
    editEndpoint: "openai/gpt-image-2/edit",
    endpoint: "openai/gpt-image-2",
    falPricing: {
      checkedAt: FAL_PRICING_CHECKED_AT,
      currency: "USD",
      endpointId: "openai/gpt-image-2",
      estimatedCostPerImageUsd: 0.211,
      source: "fal-pricing-api",
      unit: "units",
      unitPrice: 1,
    },
    maxReferenceImages: 4,
    name: "GPT Image 2",
    pricePerImageUsd: 0.211,
    pricing: "$0.211",
    sizeMode: "image_size_enum",
    supportsAspect: true,
    supportsEdit: true,
    supportsMaskImage: true,
    // fal's /edit schema names the mask `mask_url`.
    maskImageField: "mask_url",
    supportsNumImages: true,
    supportsOutputFormat: true,
    supportsQuality: true,
    supportsResolution: false,
    supportsSyncMode: true,
    // fal's schema now lists `background` on openai/gpt-image-2, but no request has
    // confirmed it returns alpha, so transparency stays on the OpenAI route.
    transparencyRoute: {
      apiKeyEnv: "OPENAI_API_KEY",
      model: "gpt-image-2",
      provider: "openai",
      supportsEdit: true,
    },
    type: "generation",
    useQueue: true,
  },
  gpt: {
    benchmark: {
      artificialAnalysis: {
        editing: { elo: 1250, rank: 5 },
        snapshotDate: AA_IMAGE_LEADERBOARD_SNAPSHOT,
        sourceUrls: AA_IMAGE_SOURCES,
        textToImage: { elo: 1310, rank: 4 },
      },
      speed: {
        medianSeconds: 34.6,
        p95Seconds: 38.3,
        source: "artificial-analysis-models",
      },
      tiers: { price: "ultra", quality: "frontier", speed: "slow" },
      useCase: "Best OpenAI edit quality with transparent PNG support",
    },
    editEndpoint: "fal-ai/gpt-image-1.5/edit",
    endpoint: "fal-ai/gpt-image-1.5",
    falPricing: {
      checkedAt: FAL_PRICING_CHECKED_AT,
      currency: "USD",
      endpointId: "fal-ai/gpt-image-1.5",
      estimatedCostPerImageUsd: 0.133,
      source: "fal-pricing-api",
      unit: "units",
      unitPrice: 1,
    },
    maxReferenceImages: 4,
    name: "GPT Image 1.5",
    pricePerImageUsd: 0.133,
    pricing: "$0.133",
    sizeMode: "gpt_size",
    supportsAspect: false,
    supportsBackground: true,
    supportsEdit: true,
    supportsMaskImage: true,
    supportsNumImages: true,
    supportsOutputFormat: true,
    supportsQuality: true,
    supportsResolution: false,
    supportsSyncMode: true,
    type: "generation",
  },
  banana2: {
    benchmark: {
      artificialAnalysis: {
        editing: { elo: 1249, rank: 7 },
        snapshotDate: AA_IMAGE_LEADERBOARD_SNAPSHOT,
        sourceUrls: AA_IMAGE_SOURCES,
        textToImage: { elo: 1320, rank: 3 },
      },
      tiers: { price: "premium", quality: "frontier", speed: "unknown" },
      useCase: "Best balance of quality, edit support, web search, and cost",
    },
    editEndpoint: "fal-ai/nano-banana-2/edit",
    endpoint: "fal-ai/nano-banana-2",
    falPricing: {
      checkedAt: FAL_PRICING_CHECKED_AT,
      currency: "USD",
      endpointId: "fal-ai/nano-banana-2",
      estimatedCostPerImageUsd: 0.08,
      source: "fal-pricing-api",
      unit: "images",
      unitPrice: 0.08,
    },
    maxReferenceImages: 4,
    name: "Nano Banana 2",
    pricePerImageUsd: 0.08,
    pricing: "$0.08",
    sizeMode: "aspect_ratio",
    supportsAspect: true,
    supportsEdit: true,
    supportsGoogleSearch: true,
    supportsLimitGenerations: true,
    supportsNumImages: true,
    supportsOutputFormat: true,
    supportsResolution: true,
    supportsSafetyTolerance: true,
    supportsSeed: true,
    supportsSyncMode: true,
    supportsThinkingLevel: true,
    supportsWebSearch: true,
    type: "generation",
  },
  banana: {
    benchmark: {
      artificialAnalysis: {
        editing: { elo: 1245, rank: 9 },
        snapshotDate: AA_IMAGE_LEADERBOARD_SNAPSHOT,
        sourceUrls: AA_IMAGE_SOURCES,
        textToImage: { elo: 1297, rank: 6 },
      },
      speed: {
        medianSeconds: 19.2,
        p95Seconds: 30.3,
        source: "artificial-analysis-models",
      },
      tiers: { price: "ultra", quality: "frontier", speed: "balanced" },
      useCase: "Premium Gemini image generation and multi-reference edits",
    },
    editEndpoint: "fal-ai/nano-banana-pro/edit",
    endpoint: "fal-ai/nano-banana-pro",
    falPricing: {
      checkedAt: FAL_PRICING_CHECKED_AT,
      currency: "USD",
      endpointId: "fal-ai/nano-banana-pro",
      estimatedCostPerImageUsd: 0.15,
      source: "fal-pricing-api",
      unit: "images",
      unitPrice: 0.15,
    },
    maxReferenceImages: 14,
    name: "Nano Banana Pro",
    pricePerImageUsd: 0.15,
    pricing: "$0.15",
    sizeMode: "aspect_ratio",
    // From fal's enums on fal-ai/nano-banana-pro and /edit.
    supportedAspects: [
      "auto",
      "21:9",
      "16:9",
      "3:2",
      "4:3",
      "5:4",
      "1:1",
      "4:5",
      "3:4",
      "2:3",
      "9:16",
    ],
    supportedResolutions: ["1K", "2K", "4K"],
    supportsAspect: true,
    supportsEdit: true,
    supportsGoogleSearch: true,
    supportsLimitGenerations: true,
    supportsNumImages: true,
    supportsOutputFormat: true,
    supportsResolution: true,
    supportsSafetyTolerance: true,
    supportsSeed: true,
    supportsSyncMode: true,
    supportsWebSearch: true,
    type: "generation",
  },
  gemini: {
    benchmark: {
      artificialAnalysis: {
        editing: { elo: 1180, rank: 29 },
        snapshotDate: AA_IMAGE_LEADERBOARD_SNAPSHOT,
        sourceUrls: AA_IMAGE_SOURCES,
      },
    },
    editEndpoint: "fal-ai/gemini-25-flash-image/edit",
    endpoint: "fal-ai/gemini-25-flash-image",
    falPricing: {
      checkedAt: FAL_PRICING_CHECKED_AT,
      currency: "USD",
      endpointId: "fal-ai/gemini-25-flash-image",
      estimatedCostPerImageUsd: 0.0398,
      source: "fal-pricing-api",
      unit: "images",
      unitPrice: 0.0398,
    },
    maxReferenceImages: 4,
    name: "Gemini 2.5 Flash",
    pricePerImageUsd: 0.0398,
    pricing: "$0.04",
    sizeMode: "aspect_ratio",
    // From fal's enums on fal-ai/gemini-25-flash-image; only /edit takes auto.
    supportedAspects: [
      "21:9",
      "16:9",
      "3:2",
      "4:3",
      "5:4",
      "1:1",
      "4:5",
      "3:4",
      "2:3",
      "9:16",
    ],
    supportsAspect: true,
    supportsEdit: true,
    supportsNumImages: true,
    supportsOutputFormat: true,
    supportsResolution: false,
    supportsSafetyTolerance: true,
    supportsSeed: true,
    supportsSyncMode: true,
    type: "generation",
  },
  gemini3: {
    benchmark: {
      artificialAnalysis: {
        editing: { elo: 1245, rank: 9 },
        snapshotDate: AA_IMAGE_LEADERBOARD_SNAPSHOT,
        sourceUrls: AA_IMAGE_SOURCES,
        textToImage: { elo: 1297, rank: 6 },
      },
    },
    editEndpoint: "fal-ai/gemini-3-pro-image-preview/edit",
    endpoint: "fal-ai/gemini-3-pro-image-preview",
    falPricing: {
      checkedAt: FAL_PRICING_CHECKED_AT,
      currency: "USD",
      endpointId: "fal-ai/gemini-3-pro-image-preview",
      estimatedCostPerImageUsd: 0.15,
      source: "fal-pricing-api",
      unit: "images",
      unitPrice: 0.15,
    },
    maxReferenceImages: 4,
    name: "Gemini 3 Pro",
    pricePerImageUsd: 0.15,
    pricing: "$0.15",
    sizeMode: "aspect_ratio",
    // From fal's enums on fal-ai/gemini-3-pro-image-preview and /edit.
    supportedAspects: [
      "auto",
      "21:9",
      "16:9",
      "3:2",
      "4:3",
      "5:4",
      "1:1",
      "4:5",
      "3:4",
      "2:3",
      "9:16",
    ],
    supportedResolutions: ["1K", "2K", "4K"],
    supportsAspect: true,
    supportsEdit: true,
    supportsNumImages: true,
    supportsOutputFormat: true,
    supportsResolution: true,
    supportsSafetyTolerance: true,
    supportsSeed: true,
    supportsSyncMode: true,
    supportsWebSearch: true,
    type: "generation",
  },
  seedream4: {
    benchmark: {
      artificialAnalysis: {
        editing: { elo: 1185, rank: 28 },
        snapshotDate: AA_IMAGE_LEADERBOARD_SNAPSHOT,
        sourceUrls: AA_IMAGE_SOURCES,
        textToImage: { elo: 1226, rank: 16 },
      },
      speed: {
        medianSeconds: 14.3,
        p95Seconds: 21,
        source: "artificial-analysis-models",
      },
      tiers: { price: "budget", quality: "best", speed: "balanced" },
      useCase: "High-ranked budget generation and large multi-reference edits",
    },
    customImageSize: { maxPixels: 16_777_216, minPixels: 921_600 },
    editEndpoint: "fal-ai/bytedance/seedream/v4/edit",
    endpoint: "fal-ai/bytedance/seedream/v4/text-to-image",
    falPricing: {
      checkedAt: FAL_PRICING_CHECKED_AT,
      currency: "USD",
      endpointId: "fal-ai/bytedance/seedream/v4/text-to-image",
      estimatedCostPerImageUsd: 0.03,
      source: "fal-pricing-api",
      unit: "images",
      unitPrice: 0.03,
    },
    maxReferenceImages: 10,
    name: "Seedream 4.0",
    pricePerImageUsd: 0.03,
    pricing: "$0.03",
    sizeMode: "image_size_enum",
    supportsAspect: true,
    supportsEdit: true,
    supportsNumImages: true,
    supportsResolution: false,
    supportsSeed: true,
    supportsSyncMode: true,
    type: "generation",
  },
  seedream45: {
    benchmark: {
      artificialAnalysis: {
        editing: { elo: 1186, rank: 26 },
        snapshotDate: AA_IMAGE_LEADERBOARD_SNAPSHOT,
        sourceUrls: AA_IMAGE_SOURCES,
        textToImage: { elo: 1203, rank: 32 },
      },
      speed: {
        medianSeconds: 18.2,
        p95Seconds: 43.3,
        source: "artificial-analysis-models",
      },
      tiers: { price: "standard", quality: "better", speed: "balanced" },
      useCase: "Cheap current Seedream model with good animation/art scores",
    },
    customImageSize: { maxPixels: 16_777_216, minPixels: 3_686_400 },
    editEndpoint: "fal-ai/bytedance/seedream/v4.5/edit",
    endpoint: "fal-ai/bytedance/seedream/v4.5/text-to-image",
    falPricing: {
      checkedAt: FAL_PRICING_CHECKED_AT,
      currency: "USD",
      endpointId: "fal-ai/bytedance/seedream/v4.5/text-to-image",
      estimatedCostPerImageUsd: 0.04,
      source: "fal-pricing-api",
      unit: "images",
      unitPrice: 0.04,
    },
    maxReferenceImages: 10,
    name: "Seedream 4.5",
    pricePerImageUsd: 0.04,
    pricing: "$0.04",
    sizeMode: "image_size_enum",
    supportsAspect: true,
    supportsEdit: true,
    supportsNumImages: true,
    supportsResolution: false,
    supportsSeed: true,
    supportsSyncMode: true,
    type: "generation",
  },
  seedream5: {
    benchmark: {
      artificialAnalysis: {
        editing: { elo: 1248, rank: 8 },
        snapshotDate: AA_IMAGE_LEADERBOARD_SNAPSHOT,
        sourceUrls: AA_IMAGE_SOURCES,
        textToImage: { elo: 1279, rank: 10 },
      },
    },
    customImageSize: {
      maxPixels: 4_194_304,
      maxRatio: 16,
      minPixels: 1_048_576,
    },
    name: "Seedream 5.0 Pro",
    endpoint: "bytedance/seedream/v5/pro/text-to-image",
    editEndpoint: "bytedance/seedream/v5/pro/edit",
    type: "generation",
    // fal tiers Seedream v5 Pro by output size: $0.0675 up to 1536², $0.135 up to 2048².
    pricing: "$0.0675 (≤1536²) / $0.135 (≤2048²)",
    pricePerImageUsd: 0.0675,
    falPricing: {
      checkedAt: FAL_PRICING_CHECKED_JUL_2026,
      currency: "USD",
      endpointId: "bytedance/seedream/v5/pro/text-to-image",
      estimatedCostPerImageUsd: 0.0675,
      source: "fal-pricing-api",
      unit: "images",
      unitPrice: 0.0675,
    },
    sizeMode: "image_size_enum",
    supportsAspect: true,
    supportsResolution: false,
    supportsEdit: true,
    supportsNumImages: true,
    supportsSeed: true,
    supportsSyncMode: true,
    maxReferenceImages: 10,
  },
  "seedream5-lite": {
    benchmark: {
      artificialAnalysis: {
        editing: { elo: 1169, rank: 32 },
        snapshotDate: AA_IMAGE_LEADERBOARD_SNAPSHOT,
        sourceUrls: AA_IMAGE_SOURCES,
      },
    },
    customImageSize: { maxPixels: 16_777_216, minPixels: 3_686_400 },
    name: "Seedream 5.0 Lite",
    endpoint: "bytedance/seedream/v5/lite/text-to-image",
    editEndpoint: "bytedance/seedream/v5/lite/edit",
    type: "generation",
    // Flat price regardless of resolution; native up to Auto 3K (~9.4MP).
    pricing: "$0.035",
    pricePerImageUsd: 0.035,
    falPricing: {
      checkedAt: FAL_PRICING_CHECKED_JUL_2026,
      currency: "USD",
      endpointId: "bytedance/seedream/v5/lite/text-to-image",
      estimatedCostPerImageUsd: 0.035,
      source: "fal-pricing-api",
      unit: "images",
      unitPrice: 0.035,
    },
    sizeMode: "image_size_enum",
    supportsAspect: true,
    supportsResolution: false,
    supportsEdit: true,
    supportsNumImages: true,
    supportsSeed: true,
    supportsSyncMode: true,
    maxReferenceImages: 10,
  },
  "flux2-max": {
    benchmark: {
      artificialAnalysis: {
        editing: { elo: 1201, rank: 19 },
        snapshotDate: AA_IMAGE_LEADERBOARD_SNAPSHOT,
        sourceUrls: AA_IMAGE_SOURCES,
        textToImage: { elo: 1225, rank: 17 },
      },
      speed: {
        medianSeconds: 31.6,
        p95Seconds: 41,
        source: "artificial-analysis-models",
      },
      tiers: { price: "premium", quality: "best", speed: "slow" },
      useCase: "Best FLUX quality and high-end editing",
    },
    customImageSize: {
      maxEdge: 2560,
      maxPixels: 4_194_304,
      minEdge: 256,
      multipleOf: 16,
    },
    editEndpoint: "fal-ai/flux-2-max/edit",
    endpoint: "fal-ai/flux-2-max",
    falPricing: {
      checkedAt: FAL_PRICING_CHECKED_AT,
      currency: "USD",
      endpointId: "fal-ai/flux-2-max",
      estimatedCostPerImageUsd: 0.07,
      source: "fal-pricing-api",
      unit: "megapixels",
      unitPrice: 0.07,
    },
    maxReferenceImages: 10,
    name: "FLUX.2 Max",
    pricePerImageUsd: 0.07,
    pricing: "$0.07/MP",
    sizeMode: "image_size_enum",
    supportsAspect: true,
    supportsEdit: true,
    supportsNumImages: false,
    supportsOutputFormat: true,
    supportsResolution: false,
    supportsSafetyChecker: true,
    supportsSafetyTolerance: true,
    supportsSeed: true,
    supportsSyncMode: true,
    type: "generation",
  },
  "flux2-pro": {
    benchmark: {
      artificialAnalysis: {
        editing: { elo: 1170, rank: 31 },
        snapshotDate: AA_IMAGE_LEADERBOARD_SNAPSHOT,
        sourceUrls: AA_IMAGE_SOURCES,
        textToImage: { elo: 1207, rank: 30 },
      },
      speed: {
        medianSeconds: 16.1,
        p95Seconds: 23.9,
        source: "artificial-analysis-models",
      },
      tiers: { price: "budget", quality: "best", speed: "balanced" },
      useCase: "Production FLUX quality at a low per-megapixel price",
    },
    customImageSize: {
      maxEdge: 2560,
      maxPixels: 4_194_304,
      minEdge: 256,
      multipleOf: 16,
    },
    editEndpoint: "fal-ai/flux-2-pro/edit",
    endpoint: "fal-ai/flux-2-pro",
    falPricing: {
      checkedAt: FAL_PRICING_CHECKED_AT,
      currency: "USD",
      endpointId: "fal-ai/flux-2-pro",
      estimatedCostPerImageUsd: 0.03,
      source: "fal-pricing-api",
      unit: "processed megapixels",
      unitPrice: 0.03,
    },
    maxReferenceImages: 10,
    name: "FLUX.2 Pro",
    pricePerImageUsd: 0.03,
    pricing: "$0.03/MP",
    sizeMode: "image_size_enum",
    supportsAspect: true,
    supportsEdit: true,
    supportsNumImages: false,
    supportsOutputFormat: true,
    supportsResolution: false,
    supportsSafetyChecker: true,
    supportsSafetyTolerance: true,
    supportsSeed: true,
    supportsSyncMode: true,
    type: "generation",
  },
  "flux2-flex": {
    benchmark: {
      artificialAnalysis: {
        snapshotDate: AA_IMAGE_LEADERBOARD_SNAPSHOT,
        sourceUrls: AA_IMAGE_SOURCES,
        textToImage: { elo: 1223, rank: 18 },
      },
      speed: {
        medianSeconds: 15.3,
        p95Seconds: 22.2,
        source: "artificial-analysis-models",
      },
      tiers: { price: "standard", quality: "best", speed: "balanced" },
      useCase: "FLUX quality with guidance and step controls",
    },
    customImageSize: {
      maxEdge: 2560,
      maxPixels: 4_194_304,
      minEdge: 256,
      multipleOf: 16,
    },
    editEndpoint: "fal-ai/flux-2-flex/edit",
    endpoint: "fal-ai/flux-2-flex",
    falPricing: {
      checkedAt: FAL_PRICING_CHECKED_AT,
      currency: "USD",
      endpointId: "fal-ai/flux-2-flex",
      estimatedCostPerImageUsd: 0.05,
      source: "fal-pricing-api",
      unit: "processed megapixels",
      unitPrice: 0.05,
    },
    maxReferenceImages: 10,
    name: "FLUX.2 Flex",
    pricePerImageUsd: 0.05,
    pricing: "$0.05/MP",
    sizeMode: "image_size_enum",
    supportedOutputFormats: ["jpeg", "png"],
    supportsAspect: true,
    supportsEdit: true,
    supportsGuidanceScale: true,
    supportsInferenceSteps: true,
    supportsNumImages: false,
    supportsOutputFormat: true,
    supportsResolution: false,
    supportsSafetyChecker: true,
    supportsSafetyTolerance: true,
    supportsSeed: true,
    supportsSyncMode: true,
    type: "generation",
  },
  "flux2-dev": {
    benchmark: {
      artificialAnalysis: {
        snapshotDate: AA_IMAGE_LEADERBOARD_SNAPSHOT,
        sourceUrls: AA_IMAGE_SOURCES,
      },
      speed: {
        medianSeconds: 4.6,
        p95Seconds: 69.6,
        source: "artificial-analysis-models",
      },
      tiers: { price: "variable", quality: "better", speed: "fast" },
      useCase: "Open FLUX.2 quality with low average cost",
    },
    customImageSize: { maxEdge: 2048, minEdge: 512 },
    editEndpoint: "fal-ai/flux-2/edit",
    endpoint: "fal-ai/flux-2",
    falPricing: {
      checkedAt: FAL_PRICING_CHECKED_AT,
      currency: "USD",
      endpointId: "fal-ai/flux-2",
      estimatedCostPerImageUsd: 0.012,
      source: "fal-pricing-api",
      unit: "compute seconds",
      unitPrice: 0.00167,
    },
    maxReferenceImages: 10,
    name: "FLUX.2 [dev]",
    pricePerImageUsd: 0.012,
    pricing: "$0.00167/sec",
    sizeMode: "image_size_enum",
    supportsAspect: true,
    supportsEdit: true,
    supportsGuidanceScale: true,
    supportsInferenceSteps: true,
    supportsNumImages: true,
    supportsOutputFormat: true,
    supportsResolution: false,
    supportsSafetyChecker: true,
    supportsSafetyTolerance: true,
    supportsSeed: true,
    supportsSyncMode: true,
    type: "generation",
  },
  "flux2-turbo": {
    customImageSize: { maxEdge: 2048, minEdge: 512 },
    endpoint: "fal-ai/flux-2/turbo",
    falPricing: {
      checkedAt: FAL_PRICING_CHECKED_JUL_2026,
      currency: "USD",
      endpointId: "fal-ai/flux-2/turbo",
      estimatedCostPerImageUsd: 0.008,
      source: "fal-pricing-api",
      unit: "megapixels",
      unitPrice: 0.008,
    },
    name: "FLUX.2 Turbo",
    pricePerImageUsd: 0.008,
    pricing: "$0.008/MP",
    sizeMode: "image_size_enum",
    supportsAspect: true,
    supportsEdit: false,
    supportsGuidanceScale: true,
    supportsNumImages: true,
    supportsOutputFormat: true,
    supportsResolution: false,
    supportsSafetyChecker: true,
    supportsSeed: true,
    supportsSyncMode: true,
    type: "generation",
  },
  flux: {
    endpoint: "fal-ai/flux-pro/v1.1-ultra",
    falPricing: {
      checkedAt: FAL_PRICING_CHECKED_AT,
      currency: "USD",
      endpointId: "fal-ai/flux-pro/v1.1-ultra",
      estimatedCostPerImageUsd: 0.06,
      source: "fal-pricing-api",
      unit: "images",
      unitPrice: 0.06,
    },
    maxReferenceImages: 1,
    name: "FLUX Pro Ultra",
    pricePerImageUsd: 0.06,
    pricing: "$0.06",
    sizeMode: "aspect_ratio",
    supportsAspect: true,
    supportsEdit: true,
    supportsEnhancePrompt: true,
    supportsImagePromptStrength: true,
    supportsNumImages: true,
    supportsOutputFormat: true,
    supportsRaw: true,
    supportsResolution: false,
    supportsSafetyTolerance: true,
    supportsSeed: true,
    supportsSyncMode: true,
    type: "generation",
  },
  "flux-fast": {
    customImageSize: {},
    endpoint: "fal-ai/flux/schnell",
    falPricing: {
      checkedAt: FAL_PRICING_CHECKED_AT,
      currency: "USD",
      endpointId: "fal-ai/flux/schnell",
      estimatedCostPerImageUsd: 0.003,
      source: "fal-pricing-api",
      unit: "megapixels",
      unitPrice: 0.003,
    },
    name: "FLUX Schnell",
    pricePerImageUsd: 0.003,
    pricing: "$0.003",
    sizeMode: "image_size_enum",
    supportsAspect: true,
    supportsEdit: false,
    supportsGuidanceScale: true,
    supportsInferenceSteps: true,
    supportsNumImages: true,
    supportsOutputFormat: true,
    supportsResolution: false,
    supportsSeed: true,
    supportsSyncMode: true,
    type: "generation",
  },
  recraft: {
    customImageSize: {},
    endpoint: "fal-ai/recraft/v3/text-to-image",
    falPricing: {
      checkedAt: FAL_PRICING_CHECKED_AT,
      currency: "USD",
      endpointId: "fal-ai/recraft/v3/text-to-image",
      estimatedCostPerImageUsd: 0.04,
      source: "fal-pricing-api",
      unit: "images",
      unitPrice: 0.04,
    },
    name: "Recraft V3",
    pricePerImageUsd: 0.04,
    pricing: "$0.04",
    sizeMode: "image_size_enum",
    supportsAspect: true,
    supportsEdit: false,
    supportsNumImages: false,
    supportsResolution: false,
    supportsStyle: true,
    supportsSyncMode: true,
    type: "generation",
  },
  reve: {
    benchmark: {
      artificialAnalysis: {
        // #2 on both boards. fal lists Reve as unlisted (not deprecated) and Motif ranks it
        // in no Task; the top editor, MAI-Image-2.5-Pro, is `mai-image-2.5-pro`.
        editing: { elo: 1263, rank: 2 },
        snapshotDate: AA_IMAGE_LEADERBOARD_SNAPSHOT,
        sourceUrls: AA_IMAGE_SOURCES,
        textToImage: { elo: 1322, rank: 2 },
      },
      tiers: { price: "premium", quality: "frontier", speed: "unknown" },
      useCase:
        "Highest-ranked editor reachable on fal; strong prompt adherence and text rendering",
    },
    editEndpoint: "fal-ai/reve/edit",
    endpoint: "fal-ai/reve/text-to-image",
    falPricing: {
      checkedAt: FAL_PRICING_CHECKED_AUG_2026,
      currency: "USD",
      endpointId: "fal-ai/reve/text-to-image",
      estimatedCostPerImageUsd: 0.04,
      source: "fal-pricing-api",
      unit: "images",
      unitPrice: 0.04,
    },
    maxReferenceImages: 1,
    name: "Reve 2.1",
    pricePerImageUsd: 0.04,
    pricing: "$0.04",
    // fal's schema takes aspect_ratio from a fixed set and has no width/height or resolution
    // parameter, so aspect is supported and resolution is not.
    sizeMode: "aspect_ratio",
    // From fal's enums on fal-ai/reve/text-to-image.
    supportedAspects: ["16:9", "9:16", "3:2", "2:3", "4:3", "3:4", "1:1"],
    supportsAspect: true,
    supportsEdit: true,
    supportsNumImages: true,
    supportsOutputFormat: true,
    supportsResolution: false,
    supportsSeed: false,
    supportsSyncMode: true,
    type: "generation",
  },
  recraft4: {
    benchmark: {
      artificialAnalysis: {
        snapshotDate: AA_IMAGE_LEADERBOARD_SNAPSHOT,
        sourceUrls: AA_IMAGE_SOURCES,
        textToImage: { elo: 1215, rank: 25 },
      },
    },
    customImageSize: {},
    endpoint: "fal-ai/recraft/v4/text-to-image",
    falPricing: {
      checkedAt: FAL_PRICING_CHECKED_JUL_2026,
      currency: "USD",
      endpointId: "fal-ai/recraft/v4/text-to-image",
      estimatedCostPerImageUsd: 0.04,
      source: "fal-pricing-api",
      unit: "images",
      unitPrice: 0.04,
    },
    name: "Recraft V4",
    pricePerImageUsd: 0.04,
    pricing: "$0.04",
    sizeMode: "image_size_enum",
    supportsAspect: true,
    supportsEdit: false,
    supportsNumImages: false,
    supportsResolution: false,
    // fal's v4 schema has no `style`; V3 is the Recraft that takes one.
    supportsSyncMode: true,
    type: "generation",
  },
  ideogram: {
    customImageSize: {},
    endpoint: "fal-ai/ideogram/v3",
    falPricing: {
      checkedAt: FAL_PRICING_CHECKED_AT,
      currency: "USD",
      endpointId: "fal-ai/ideogram/v3",
      estimatedCostPerImageUsd: 0.03,
      source: "fal-pricing-api",
      unit: "images",
      unitPrice: 0.03,
    },
    name: "Ideogram V3",
    pricePerImageUsd: 0.03,
    pricing: "$0.03",
    sizeMode: "image_size_enum",
    supportsAspect: true,
    supportsEdit: false,
    supportsExpandPrompt: true,
    supportsNegativePrompt: true,
    supportsNumImages: true,
    supportsRenderingSpeed: true,
    supportsResolution: false,
    supportsSeed: true,
    supportsStyle: true,
    supportsSyncMode: true,
    type: "generation",
  },
  ideogram4: {
    benchmark: {
      artificialAnalysis: {
        snapshotDate: AA_IMAGE_LEADERBOARD_SNAPSHOT,
        sourceUrls: AA_IMAGE_SOURCES,
        textToImage: { elo: 1220, rank: 19 },
      },
    },
    customImageSize: { maxEdge: 3840, minEdge: 512, multipleOf: 16 },
    name: "Ideogram V4",
    endpoint: "ideogram/v4",
    type: "generation",
    // fal bills v4 per output megapixel by rendering speed: TURBO $0.03, BALANCED
    // $0.06, QUALITY $0.10 (plus a flat $0.03 when prompt expansion is used).
    // Headline uses the TURBO 1MP rate, matching how ideogram v3 is modeled.
    pricing: "$0.03",
    pricePerImageUsd: 0.03,
    falPricing: {
      checkedAt: FAL_PRICING_CHECKED_JUL_2026,
      currency: "USD",
      endpointId: "ideogram/v4",
      estimatedCostPerImageUsd: 0.03,
      source: "fal-pricing-api",
      unit: "megapixels",
      unitPrice: 0.03,
    },
    sizeMode: "image_size_enum",
    supportsAspect: true,
    supportsResolution: false,
    supportsEdit: false,
    supportsNumImages: true,
    supportsRenderingSpeed: true,
    supportsSeed: true,
    supportsOutputFormat: true,
    supportedOutputFormats: ["jpeg", "png"],
    supportsSafetyChecker: true,
    supportsSyncMode: true,
  },
  "grok-image": {
    benchmark: {
      artificialAnalysis: {
        editing: { elo: 1214, rank: 16 },
        snapshotDate: AA_IMAGE_LEADERBOARD_SNAPSHOT,
        sourceUrls: AA_IMAGE_SOURCES,
        textToImage: { elo: 1216, rank: 23 },
      },
      speed: {
        medianSeconds: 5.1,
        p95Seconds: 6.5,
        source: "artificial-analysis-models",
      },
      tiers: { price: "budget", quality: "best", speed: "fast" },
      useCase: "Very fast, cheap generation and edits",
    },
    editEndpoint: "xai/grok-imagine-image/edit",
    endpoint: "xai/grok-imagine-image",
    falPricing: {
      checkedAt: FAL_PRICING_CHECKED_AT,
      currency: "USD",
      endpointId: "xai/grok-imagine-image",
      estimatedCostPerImageUsd: 0.02,
      source: "fal-pricing-api",
      unit: "images",
      unitPrice: 0.02,
    },
    // fal's edit schema: "A maximum of 3 images are supported."
    maxReferenceImages: 3,
    name: "Grok Imagine Image",
    pricePerImageUsd: 0.02,
    pricing: "$0.02",
    sizeMode: "aspect_ratio",
    // From fal's enums on xai/grok-imagine-image; only /edit takes auto.
    supportedAspects: ["16:9", "4:3", "3:2", "1:1", "2:3", "3:4", "9:16"],
    supportedResolutions: ["1K", "2K"],
    supportsAspect: true,
    supportsEdit: true,
    supportsNumImages: true,
    supportsOutputFormat: true,
    supportsResolution: true,
    supportsSyncMode: true,
    type: "generation",
  },
  qwen: {
    benchmark: {
      artificialAnalysis: {
        snapshotDate: AA_IMAGE_LEADERBOARD_SNAPSHOT,
        sourceUrls: AA_IMAGE_SOURCES,
      },
      speed: {
        medianSeconds: 23.3,
        p95Seconds: 491,
        source: "artificial-analysis-models",
      },
      tiers: { price: "budget", quality: "better", speed: "slow" },
      useCase: "Low-cost open-weight text and design generation",
    },
    customImageSize: {},
    endpoint: "fal-ai/qwen-image",
    falPricing: {
      checkedAt: FAL_PRICING_CHECKED_AT,
      currency: "USD",
      endpointId: "fal-ai/qwen-image",
      estimatedCostPerImageUsd: 0.02,
      source: "fal-pricing-api",
      unit: "megapixels",
      unitPrice: 0.02,
    },
    name: "Qwen Image",
    pricePerImageUsd: 0.02,
    pricing: "$0.02/MP",
    sizeMode: "image_size_enum",
    supportsAspect: true,
    supportsEdit: false,
    supportsNumImages: true,
    supportsOutputFormat: true,
    supportsResolution: false,
    supportsSeed: true,
    supportsSyncMode: true,
    type: "generation",
  },
  qwen3: {
    benchmark: {
      artificialAnalysis: {
        editing: { elo: 1218, rank: 15 },
        snapshotDate: AA_IMAGE_LEADERBOARD_SNAPSHOT,
        sourceUrls: AA_IMAGE_SOURCES,
        textToImage: { elo: 1272, rank: 11 },
      },
      tiers: { price: "budget", quality: "better", speed: "unknown" },
      useCase: "Strong quality per dollar - 11th on text-to-image at $30/1k",
    },
    customImageSize: { maxPixels: 4_194_304, minPixels: 262_144 },
    endpoint: "alibaba/qwen-image-3/text-to-image",
    falPricing: {
      checkedAt: FAL_PRICING_CHECKED_SEP_2026,
      currency: "USD",
      endpointId: "alibaba/qwen-image-3/text-to-image",
      estimatedCostPerImageUsd: 0.04,
      source: "fal-pricing-api",
      unit: "images",
      unitPrice: 0.04,
    },
    name: "Qwen Image 3",
    pricePerImageUsd: 0.04,
    // Motif sends a 1K image_size; 2K output costs $0.075.
    pricing: "$0.04 (1K) / $0.075 (2K)",
    sizeMode: "image_size_enum",
    supportsAspect: true,
    supportsEdit: false,
    supportsNegativePrompt: true,
    supportsNumImages: true,
    supportsOutputFormat: true,
    supportsResolution: false,
    supportsSafetyChecker: true,
    supportsSeed: true,
    type: "generation",
  },

  "mai-image-2.5-pro": {
    benchmark: {
      artificialAnalysis: {
        editing: { elo: 1272, rank: 1 },
        snapshotDate: AA_IMAGE_LEADERBOARD_SNAPSHOT,
        sourceUrls: AA_IMAGE_SOURCES,
        textToImage: { elo: 1293, rank: 7 },
      },
      useCase: "Highest-ranked image editor, single reference image",
    },
    editEndpoint: "microsoft/mai-image-2.5-pro/edit",
    editImagesField: "image_url",
    endpoint: "microsoft/mai-image-2.5-pro",
    falPricing: {
      checkedAt: FAL_PRICING_CHECKED_SEP_2026,
      currency: "USD",
      endpointId: "microsoft/mai-image-2.5-pro",
      estimatedCostPerImageUsd: 0.17,
      source: "fal-pricing-api",
      unit: "images",
      unitPrice: 0.17,
    },
    maxReferenceImages: 1,
    name: "MAI Image 2.5 Pro",
    // fal bills tokens: text $7.50/M in, image $162/M out. It quotes ~$0.17 per
    // text-to-image image and ~$0.18-$0.27 per edit with one input image.
    pricePerImageUsd: 0.17,
    pricing: "~$0.17 (edit ~$0.18-$0.27)",
    // fal's schema takes aspect_ratio from auto, 1:1, 4:3, 3:4, 16:9, 9:16, 3:2, 2:3.
    sizeMode: "aspect_ratio",
    // From fal's enums on microsoft/mai-image-2.5-pro and /edit.
    supportedAspects: [
      "auto",
      "1:1",
      "4:3",
      "3:4",
      "16:9",
      "9:16",
      "3:2",
      "2:3",
    ],
    supportsAspect: true,
    supportsEdit: true,
    supportsNumImages: true,
    supportsOutputFormat: true,
    supportsResolution: false,
    supportsSyncMode: true,
    type: "generation",
  },
  "banana2-lite": {
    benchmark: {
      artificialAnalysis: {
        snapshotDate: AA_IMAGE_LEADERBOARD_SNAPSHOT,
        sourceUrls: AA_IMAGE_SOURCES,
        textToImage: { elo: 1289, rank: 8 },
      },
    },
    endpoint: "google/nano-banana-2-lite",
    name: "Nano Banana 2 Lite",
    // fal lists no edit endpoint for it; `/edit` answers a schema but is unlisted and unpriced.
    // Projected: a 1K image is 1,290 output tokens at $37.50/M, about $0.048.
    pricing:
      "Token-based: text $0.3125/M input, $1.875/M output; image $0.3125/M input, $37.50/M output; fixed 1K output (~$0.048)",
    pricePerImageUsd: 0.048,
    sizeMode: "aspect_ratio",
    supportsAspect: true,
    supportsEdit: false,
    supportsLimitGenerations: true,
    supportsNumImages: true,
    supportsOutputFormat: true,
    supportsResolution: false,
    supportsSafetyTolerance: true,
    supportsSeed: true,
    supportsSyncMode: true,
    supportsThinkingLevel: true,
    type: "generation",
  },
  "ideogram3-transparent": {
    endpoint: "fal-ai/ideogram/v3/generate-transparent",
    falPricing: {
      checkedAt: FAL_PRICING_CHECKED_SEP_2026,
      currency: "USD",
      endpointId: "fal-ai/ideogram/v3/generate-transparent",
      estimatedCostPerImageUsd: 0.06,
      source: "fal-pricing-api",
      unit: "images",
      unitPrice: 0.06,
    },
    name: "Ideogram V3 Transparent",
    // Priced at fal's default BALANCED rendering speed, which Motif leaves unset.
    pricePerImageUsd: 0.06,
    pricing: "$0.03 TURBO / $0.06 BALANCED / $0.09 QUALITY",
    sizeMode: "aspect_ratio",
    // From fal's enums on fal-ai/ideogram/v3/generate-transparent.
    supportedAspects: [
      "16:9",
      "9:16",
      "3:2",
      "2:3",
      "4:3",
      "3:4",
      "5:4",
      "4:5",
      "1:1",
    ],
    supportsAspect: true,
    supportsEdit: false,
    supportsExpandPrompt: true,
    supportsNegativePrompt: true,
    supportsNumImages: true,
    supportsRenderingSpeed: true,
    supportsResolution: false,
    supportsSeed: true,
    supportsSyncMode: true,
    transparentOutput: true,
    type: "generation",
  },
  recraft41: {
    customImageSize: {},
    endpoint: "fal-ai/recraft/v4.1/text-to-image",
    falPricing: {
      checkedAt: FAL_PRICING_CHECKED_SEP_2026,
      currency: "USD",
      endpointId: "fal-ai/recraft/v4.1/text-to-image",
      estimatedCostPerImageUsd: 0.035,
      source: "fal-pricing-api",
      unit: "images",
      unitPrice: 0.035,
    },
    name: "Recraft V4.1",
    pricePerImageUsd: 0.035,
    pricing: "$0.035",
    sizeMode: "image_size_enum",
    supportsAspect: true,
    supportsEdit: false,
    supportsNumImages: false,
    supportsResolution: false,
    supportsSafetyChecker: true,
    type: "generation",
  },
  "grok-image-2": {
    editEndpoint: "xai/grok-imagine-image/v2.0/edit",
    endpoint: "xai/grok-imagine-image/v2.0/text-to-image",
    falPricing: {
      checkedAt: FAL_PRICING_CHECKED_SEP_2026,
      currency: "USD",
      endpointId: "xai/grok-imagine-image/v2.0/text-to-image",
      estimatedCostPerImageUsd: 0.06,
      source: "fal-pricing-api",
      unit: "images",
      unitPrice: 0.06,
    },
    // fal's edit schema: "A maximum of 3 images are supported."
    maxReferenceImages: 3,
    name: "Grok Imagine Image 2.0",
    // Motif leaves quality at fal's default, medium, and sends 2K unless asked.
    // Edits add $0.01 per input image.
    pricePerImageUsd: 0.06,
    pricing: "$0.06 (1K) / $0.08 (2K) at medium quality",
    sizeMode: "aspect_ratio",
    // From fal's enums on xai/grok-imagine-image/v2.0; only /edit takes auto.
    supportedAspects: ["16:9", "4:3", "3:2", "1:1", "2:3", "3:4", "9:16"],
    supportedResolutions: ["1K", "2K"],
    supportsAspect: true,
    supportsEdit: true,
    supportsNumImages: true,
    supportsOutputFormat: true,
    supportsResolution: true,
    supportsSyncMode: true,
    type: "generation",
  },

  // ─── Video Models ─────────────────────────────────────────────

  kling: {
    endpoint: "fal-ai/kling-video/v3/pro/image-to-video",
    name: "Kling v3 Pro",
    pricing: "$0.11/sec",
    sizeMode: "none",
    supportsAspect: false,
    supportsEdit: false,
    supportsNumImages: false,
    supportsResolution: false,
    type: "video",
  },
  "kling-turbo": {
    endpoint: "fal-ai/kling-video/v3/turbo/pro/image-to-video",
    name: "Kling v3 Turbo Pro",
    pricing: "$0.14/sec",
    sizeMode: "none",
    supportsAspect: false,
    supportsEdit: false,
    supportsNumImages: false,
    supportsResolution: false,
    type: "video",
  },

  // ─── Utility Models ───────────────────────────────────────────

  clarity: {
    endpoint: "fal-ai/clarity-upscaler",
    name: "Clarity Upscaler",
    pricing: "$0.03/MP",
    supportsAspect: false,
    supportsEdit: false,
    supportsNumImages: false,
    supportsResolution: false,
    type: "utility",
  },
  crystal: {
    endpoint: "clarityai/crystal-upscaler",
    name: "Crystal Upscaler",
    pricing: "$0.02",
    supportsAspect: false,
    supportsEdit: false,
    supportsNumImages: false,
    supportsResolution: false,
    type: "utility",
  },
  rmbg: {
    endpoint: "fal-ai/birefnet",
    name: "BiRefNet (Background Removal)",
    pricing: "$0.02",
    supportsAspect: false,
    supportsEdit: false,
    supportsNumImages: false,
    supportsResolution: false,
    type: "utility",
  },
  bria: {
    endpoint: "fal-ai/bria/background/remove",
    name: "Bria RMBG 2.0",
    pricing: "$0.02",
    supportsAspect: false,
    supportsEdit: false,
    supportsNumImages: false,
    supportsResolution: false,
    type: "utility",
  },
};

export const GENERATION_MODELS = [
  "flare",
  "sunburst",
  "gpt2",
  "gpt",
  "banana2",
  "banana",
  "gemini",
  "gemini3",
  "seedream4",
  "seedream45",
  "seedream5",
  "seedream5-lite",
  "flux2-max",
  "flux2-pro",
  "flux2-flex",
  "flux2-dev",
  "flux2-turbo",
  "flux",
  "flux-fast",
  "recraft",
  "recraft4",
  "ideogram",
  "ideogram4",
  "grok-image",
  "grok-image-2",
  "qwen",
  "qwen3",
  "mai-image-2.5-pro",
  "banana2-lite",
  "ideogram3-transparent",
  "recraft41",
] as const;

/** Models whose fal endpoints support image editing (vary/edit flows). */
export const EDIT_CAPABLE_MODELS = GENERATION_MODELS.filter(
  (id) => MODELS[id]?.supportsEdit === true
);

export const UTILITY_MODELS = ["clarity", "crystal", "rmbg", "bria"] as const;

export const VIDEO_MODELS = ["kling", "kling-turbo"] as const;

export type GenerationModelName = (typeof GENERATION_MODELS)[number];

/** Recraft v3 style presets. Pass as the `style` field in GenerateOptions. */
export const RECRAFT_STYLES = [
  // Realistic
  "realistic_image",
  "realistic_image/b_and_w",
  "realistic_image/enterprise",
  "realistic_image/hard_flash",
  "realistic_image/hdr",
  "realistic_image/motion_blur",
  "realistic_image/natural_light",
  "realistic_image/studio_portrait",
  "realistic_image/long_exposure",
  // Digital illustration
  "digital_illustration",
  "digital_illustration/2d_art_poster",
  "digital_illustration/2d_art_poster_2",
  "digital_illustration/engraving_color",
  "digital_illustration/grain",
  "digital_illustration/hand_drawn",
  "digital_illustration/hand_drawn_outline",
  "digital_illustration/handmade_3d",
  "digital_illustration/infantile_sketch",
  "digital_illustration/pixel_art",
  "digital_illustration/psychedelic",
  "digital_illustration/seamless",
  "digital_illustration/voxel",
  "digital_illustration/watercolor",
  // Vector illustration
  "vector_illustration",
  "vector_illustration/cartoon",
  "vector_illustration/doodle_line_art",
  "vector_illustration/engraving",
  "vector_illustration/flat_2",
  "vector_illustration/kawaii",
  "vector_illustration/line_art",
  "vector_illustration/line_circuit",
  "vector_illustration/linocut",
  "vector_illustration/zentangle",
] as const;

/** Ideogram v3 top-level style categories. Pass as the `style` field in GenerateOptions. */
export const IDEOGRAM_STYLES = [
  "AUTO",
  "GENERAL",
  "REALISTIC",
  "DESIGN",
] as const;
