// Tools that operate on the whole frame: background removal, upscaling, and
// restoration (denoise, sharpen, colourise, repair).
//
// Part of the FAL_TOOLS registry; `../tools` assembles the groups and is the
// module every consumer imports.

import type { FalToolConfig } from "../tool-types";

export const BACKGROUND_TOOLS = {
  "ben-v2": {
    category: "background",
    description: "Fast, high-quality background removal for images.",
    endpoint: "fal-ai/ben/v2/image",
    inputField: "image_url",
    inputKind: "image",
    name: "BEN v2 Background Removal",
    outputKeys: ["image"],
    price: { kind: "megapixel", usd: 0.025 },
    pricing: "$0.025/megapixel",
    sourceUrl: "https://fal.ai/models/fal-ai/ben/v2/image",
    task: "image background removal",
  },
  birefnet: {
    category: "background",
    defaultOptions: {
      model: "General Use (Light)",
      operating_resolution: "1024x1024",
      output_format: "png",
      refine_foreground: true,
    },
    description:
      "High-resolution dichotomous image segmentation and background removal.",
    endpoint: "fal-ai/birefnet/v2",
    inputField: "image_url",
    inputKind: "image",
    name: "BirefNet Background Removal",
    outputKeys: ["image", "mask_image"],
    price: { kind: "metered" },
    pricing: "$0/compute-second listed by fal",
    sourceUrl: "https://fal.ai/models/fal-ai/birefnet/v2",
    task: "image background removal",
  },
  "bria-rmbg": {
    category: "background",
    description: "Commercial-safe background removal for images.",
    endpoint: "fal-ai/bria/background/remove",
    inputField: "image_url",
    inputKind: "image",
    name: "Bria RMBG 2.0",
    outputKeys: ["image"],
    price: { kind: "call", usd: 0.018 },
    pricing: "$0.018/generation",
    sourceUrl: "https://fal.ai/models/fal-ai/bria/background/remove",
    task: "image background removal",
  },
  "bria-video-rmbg": {
    category: "background",
    defaultOptions: {
      background_color: "Black",
      output_container_and_codec: "webm_vp9",
      preserve_audio: true,
    },
    description: "Remove video backgrounds with configurable output container.",
    endpoint: "bria/video/background-removal",
    inputField: "video_url",
    inputKind: "video",
    name: "Bria Video Background Removal",
    outputKeys: ["video"],
    price: { kind: "second", usd: 0.00425 },
    pricing: "$0.00425/sec",
    queued: true,
    sourceUrl: "https://fal.ai/models/bria/video/background-removal",
    task: "video background removal",
  },
  ddcolor: {
    category: "restoration",
    description: "Colourise black-and-white photographs.",
    endpoint: "fal-ai/ddcolor",
    inputField: "image_url",
    inputKind: "image",
    name: "DDColor Colourisation",
    outputKeys: ["image"],
    price: { kind: "megapixel", usd: 0.001 },
    pricing: "$0.001/megapixel",
    sourceUrl: "https://fal.ai/models/fal-ai/ddcolor",
    task: "photo colourisation",
  },
  rembg: {
    category: "background",
    defaultOptions: {
      crop_to_bbox: false,
    },
    description: "Generic image background removal utility.",
    endpoint: "fal-ai/imageutils/rembg",
    inputField: "image_url",
    inputKind: "image",
    name: "Remove Background",
    outputKeys: ["image"],
    price: { kind: "metered" },
    pricing: "$0/compute-second listed by fal",
    sourceUrl: "https://fal.ai/models/fal-ai/imageutils/rembg",
    task: "image background removal",
  },
  "seedvr-upscale": {
    category: "restoration",
    defaultOptions: {
      output_format: "png",
    },
    description: "Diffusion image restoration and upscaling with SeedVR.",
    endpoint: "fal-ai/seedvr/upscale/image",
    inputField: "image_url",
    inputKind: "image",
    name: "SeedVR Image Upscale",
    outputKeys: ["image"],
    price: { kind: "megapixel", usd: 0.001 },
    pricing: "$0.001/megapixel",
    queued: true,
    sourceUrl: "https://fal.ai/models/fal-ai/seedvr/upscale/image",
    task: "image restoration and upscaling",
  },
  "topaz-adjust": {
    category: "restoration",
    defaultOptions: {
      output_format: "png",
    },
    description: "Topaz exposure, white balance, and colour adjustment.",
    endpoint: "topaz/adjust/image",
    inputField: "image_url",
    inputKind: "image",
    name: "Topaz Adjust",
    outputKeys: ["image"],
    price: { kind: "megapixel", usd: 0.08 / 24 },
    pricing: "$0.08 per 24 output megapixels",
    queued: true,
    sourceUrl: "https://fal.ai/models/topaz/adjust/image",
    task: "tonal adjustment",
  },
  "topaz-creative": {
    category: "restoration",
    defaultOptions: {
      output_format: "png",
    },
    description:
      "Topaz Bloom upscaling, which reimagines detail rather than preserving it.",
    endpoint: "topaz/upscale/image/creative",
    inputField: "image_url",
    inputKind: "image",
    name: "Topaz Creative Upscale",
    outputKeys: ["image"],
    price: { kind: "megapixel", usd: 0.96 / 24 },
    pricing: "$0.96 per 24 output megapixels",
    queued: true,
    sourceUrl: "https://fal.ai/models/topaz/upscale/image/creative",
    task: "creative image upscaling",
  },
  "topaz-denoise": {
    category: "restoration",
    defaultOptions: {
      output_format: "png",
    },
    description: "Topaz noise reduction at source resolution.",
    endpoint: "topaz/denoise/image",
    inputField: "image_url",
    inputKind: "image",
    name: "Topaz Denoise",
    outputKeys: ["image"],
    price: { kind: "megapixel", usd: 0.08 / 24 },
    pricing:
      "$0.08 per 24 output megapixels at the default Normal model; $0.16 with Denoise Max",
    queued: true,
    sourceUrl: "https://fal.ai/models/topaz/denoise/image",
    task: "image denoising",
  },
  "topaz-generative": {
    category: "restoration",
    defaultOptions: {
      output_format: "png",
    },
    description:
      "Topaz Wonder upscaling, which synthesises plausible detail as it enlarges.",
    endpoint: "topaz/upscale/image/generative",
    inputField: "image_url",
    inputKind: "image",
    name: "Topaz Generative Upscale",
    outputKeys: ["image"],
    price: { kind: "megapixel", usd: 0.24 / 24 },
    pricing:
      "$0.24 per 24 output megapixels at the default Wonder 3; $0.48 with Wonder, Wonder 2, Standard MAX, Redefine or Recover 3",
    queued: true,
    sourceUrl: "https://fal.ai/models/topaz/upscale/image/generative",
    task: "generative image upscaling",
  },
  "topaz-image": {
    category: "upscale",
    defaultOptions: {
      model: "Standard V2",
      output_format: "jpeg",
      upscale_factor: 2,
    },
    description: "Professional Topaz image enhancement and upscaling.",
    endpoint: "fal-ai/topaz/upscale/image",
    inputField: "image_url",
    inputKind: "image",
    name: "Topaz Image Upscale",
    outputKeys: ["image"],
    price: { kind: "megapixel", usd: 0.08 / 24 },
    pricing:
      "$0.08 for output up to 24MP; $0.16 to 48MP, $0.32 to 96MP, up to $1.36 at 512MP",
    queued: true,
    sourceUrl: "https://fal.ai/models/fal-ai/topaz/upscale/image",
    task: "image enhancement",
  },
  "topaz-precision": {
    category: "restoration",
    defaultOptions: {
      output_format: "png",
    },
    description:
      "Topaz upscaling that preserves the original detail rather than inventing it.",
    endpoint: "topaz/upscale/image/precision",
    inputField: "image_url",
    inputKind: "image",
    name: "Topaz Precision Upscale",
    outputKeys: ["image"],
    price: { kind: "megapixel", usd: 0.08 / 24 },
    pricing: "$0.08 per 24 output megapixels, any precision model",
    queued: true,
    sourceUrl: "https://fal.ai/models/topaz/upscale/image/precision",
    task: "faithful image upscaling",
  },
  "topaz-restore": {
    category: "restoration",
    defaultOptions: {
      output_format: "png",
    },
    description:
      "Topaz restoration of damaged or degraded photographs at source resolution.",
    endpoint: "topaz/restore/image",
    inputField: "image_url",
    inputKind: "image",
    name: "Topaz Restore",
    outputKeys: ["image"],
    price: { kind: "megapixel", usd: 0.48 / 24 },
    pricing:
      "$0.48 per 24 output megapixels at the default Recover 3; $0.08 with Dust-Scratch V2",
    queued: true,
    sourceUrl: "https://fal.ai/models/topaz/restore/image",
    task: "photo restoration",
  },
  "topaz-sharpen": {
    category: "restoration",
    defaultOptions: {
      output_format: "png",
    },
    description: "Topaz deblurring and sharpening at source resolution.",
    endpoint: "topaz/sharpen/image",
    inputField: "image_url",
    inputKind: "image",
    name: "Topaz Sharpen",
    outputKeys: ["image"],
    price: { kind: "megapixel", usd: 0.08 / 24 },
    pricing:
      "$0.08 per 24 output megapixels at the default Standard model; $0.16 with Super Focus",
    queued: true,
    sourceUrl: "https://fal.ai/models/topaz/sharpen/image",
    task: "image sharpening",
  },
  "topaz-transparent": {
    category: "restoration",
    description: "Topaz upscaling that preserves the alpha channel end to end.",
    endpoint: "topaz/upscale/image/transparent",
    inputField: "image_url",
    inputKind: "image",
    name: "Topaz Transparent Upscale",
    outputKeys: ["image"],
    price: { kind: "megapixel", usd: 0.08 / 24 },
    pricing: "$0.08 per 24 output megapixels",
    queued: true,
    sourceUrl: "https://fal.ai/models/topaz/upscale/image/transparent",
    task: "transparent image upscaling",
  },
  "topaz-video": {
    category: "upscale",
    defaultOptions: {
      model: "Proteus",
      upscale_factor: 2,
    },
    description: "Professional Topaz video enhancement and upscaling.",
    endpoint: "fal-ai/topaz/upscale/video",
    inputField: "video_url",
    inputKind: "video",
    name: "Topaz Video Upscale",
    outputKeys: ["video"],
    price: { kind: "second", usd: 0.01 },
    pricing:
      "$0.01/sec up to 720p; $0.02 to 1080p, $0.08 above, doubled at 60fps, halved with Gaia 2",
    queued: true,
    sourceUrl: "https://fal.ai/models/fal-ai/topaz/upscale/video",
    task: "video enhancement",
  },
} as const satisfies Record<string, FalToolConfig>;
