// Tools that extract structure for downstream conditioning: ControlNet-style
// preprocessors, depth estimation, and segmentation.
//
// Part of the FAL_TOOLS registry; `../tools` assembles the groups and is the
// module every consumer imports.

import type { FalToolConfig } from "../tool-types";

export const STRUCTURE_TOOLS = {
  "depth-anything": {
    category: "preprocess",
    description: "Generate Depth Anything v2 depth maps from input images.",
    endpoint: "fal-ai/image-preprocessors/depth-anything/v2",
    inputField: "image_url",
    inputKind: "image",
    name: "Depth Anything v2 Preprocessor",
    outputKeys: ["image"],
    price: { kind: "metered" },
    pricing: "$0/compute-second listed by fal",
    sourceUrl:
      "https://fal.ai/models/fal-ai/image-preprocessors/depth-anything/v2",
    task: "depth preprocessing",
  },
  dwpose: {
    category: "preprocess",
    description: "Extract body, hand, and face pose skeletons from an image.",
    endpoint: "fal-ai/dwpose",
    inputField: "image_url",
    inputKind: "image",
    name: "DWPose Estimation",
    outputKeys: ["image"],
    price: { kind: "second", usd: 0.0006 },
    pricing: "$0.0006/compute-second",
    sourceUrl: "https://fal.ai/models/fal-ai/dwpose",
    task: "pose preprocessing",
  },
  hed: {
    category: "preprocess",
    description: "Generate HED soft edge maps for ControlNet-style workflows.",
    endpoint: "fal-ai/image-preprocessors/hed",
    inputField: "image_url",
    inputKind: "image",
    name: "HED Edge Preprocessor",
    outputKeys: ["image"],
    price: { kind: "metered" },
    pricing: "$0/compute-second listed by fal",
    sourceUrl: "https://fal.ai/models/fal-ai/image-preprocessors/hed",
    task: "edge preprocessing",
  },
  lineart: {
    category: "preprocess",
    defaultOptions: {
      coarse: false,
    },
    description: "Generate line art/control-style edges from an input image.",
    endpoint: "fal-ai/image-preprocessors/lineart",
    inputField: "image_url",
    inputKind: "image",
    name: "Line Art Preprocessor",
    outputKeys: ["image"],
    price: { kind: "metered" },
    pricing: "$0/compute-second listed by fal",
    sourceUrl: "https://fal.ai/models/fal-ai/image-preprocessors/lineart",
    task: "image preprocessing",
  },
  "marigold-depth": {
    category: "depth",
    defaultOptions: {
      ensemble_size: 10,
      num_inference_steps: 10,
    },
    description: "Create depth maps using Marigold depth estimation.",
    endpoint: "fal-ai/imageutils/marigold-depth",
    inputField: "image_url",
    inputKind: "image",
    name: "Marigold Depth Estimation",
    outputKeys: ["image"],
    price: { kind: "metered" },
    pricing: "$0/compute-second listed by fal",
    sourceUrl: "https://fal.ai/models/fal-ai/imageutils/marigold-depth",
    task: "depth map",
  },
  "midas-depth": {
    category: "depth",
    defaultOptions: {
      a: Math.PI * 2,
      bg_th: 0.1,
    },
    description: "Create MiDaS depth maps from input images.",
    endpoint: "fal-ai/imageutils/depth",
    inputField: "image_url",
    inputKind: "image",
    name: "MiDaS Depth Estimation",
    outputKeys: ["image"],
    price: { kind: "metered" },
    pricing: "$0/compute-second listed by fal",
    sourceUrl: "https://fal.ai/models/fal-ai/imageutils/depth",
    task: "depth map",
  },
  "midas-preprocessor": {
    category: "preprocess",
    description: "Generate MiDaS depth and normal maps for image workflows.",
    endpoint: "fal-ai/image-preprocessors/midas",
    inputField: "image_url",
    inputKind: "image",
    name: "MiDaS Preprocessor",
    outputKeys: ["depth_map", "normal_map"],
    price: { kind: "metered" },
    pricing: "$0/compute-second listed by fal",
    sourceUrl: "https://fal.ai/models/fal-ai/image-preprocessors/midas",
    task: "depth and normal preprocessing",
  },
  mlsd: {
    category: "preprocess",
    description:
      "Detect straight line segments for architectural and interior control maps.",
    endpoint: "fal-ai/image-preprocessors/mlsd",
    inputField: "image_url",
    inputKind: "image",
    name: "M-LSD Line Preprocessor",
    outputKeys: ["image"],
    price: { kind: "metered" },
    pricing: "$0/compute-second listed by fal",
    sourceUrl: "https://fal.ai/models/fal-ai/image-preprocessors/mlsd",
    task: "line segment preprocessing",
  },
  pidi: {
    category: "preprocess",
    description: "Generate PiDiNet soft edge maps from an input image.",
    endpoint: "fal-ai/image-preprocessors/pidi",
    inputField: "image_url",
    inputKind: "image",
    name: "PiDiNet Edge Preprocessor",
    outputKeys: ["image"],
    price: { kind: "metered" },
    pricing: "$0/compute-second listed by fal",
    sourceUrl: "https://fal.ai/models/fal-ai/image-preprocessors/pidi",
    task: "edge preprocessing",
  },
  "sam-preprocessor": {
    category: "preprocess",
    description:
      "Generate a SAM segmentation map for ControlNet-style workflows.",
    endpoint: "fal-ai/image-preprocessors/sam",
    inputField: "image_url",
    inputKind: "image",
    name: "SAM Preprocessor",
    outputKeys: ["image"],
    price: { kind: "metered" },
    pricing: "$0/compute-second listed by fal",
    sourceUrl: "https://fal.ai/models/fal-ai/image-preprocessors/sam",
    task: "segmentation preprocessing",
  },
  "sam2-auto": {
    category: "segmentation",
    defaultOptions: {
      min_mask_region_area: 100,
      output_format: "png",
      points_per_side: 32,
      pred_iou_thresh: 0.88,
      stability_score_thresh: 0.95,
    },
    description:
      "Automatically segment an image into combined and individual masks.",
    endpoint: "fal-ai/sam2/auto-segment",
    inputField: "image_url",
    inputKind: "image",
    name: "SAM 2 Auto Segment",
    outputKeys: ["combined_mask", "individual_masks"],
    price: { kind: "metered" },
    pricing: "$0/compute-second listed by fal",
    queued: true,
    sourceUrl: "https://fal.ai/models/fal-ai/sam2/auto-segment",
    task: "automatic image segmentation",
  },
  "sam3-1-image": {
    category: "segmentation",
    defaultOptions: {
      apply_mask: true,
      max_masks: 3,
      output_format: "png",
    },
    description:
      "Segment image objects with text, point, or box prompts. SAM 3.1 adds Object Multiplex for faster multi-object tracking.",
    endpoint: "fal-ai/sam-3-1/image",
    inputField: "image_url",
    inputKind: "image",
    name: "SAM 3.1 Image",
    outputKeys: ["image", "masks", "metadata", "scores", "boxes"],
    price: { kind: "call", usd: 0.01 },
    pricing: "$0.01/request",
    sourceUrl: "https://fal.ai/models/fal-ai/sam-3-1/image",
    task: "promptable image segmentation",
  },
  "sam3-1-video": {
    category: "segmentation",
    defaultOptions: {
      apply_mask: true,
      prompt: "person",
    },
    description:
      "SAM 3.1 video segmentation with Object Multiplex tracking for multiple objects.",
    endpoint: "fal-ai/sam-3-1/video",
    inputField: "video_url",
    inputKind: "video",
    name: "SAM 3.1 Video",
    outputKeys: ["video", "boundingbox_frames_zip"],
    price: { kind: "metered" },
    pricing: "$0.01/16 frames of video input",
    queued: true,
    sourceUrl: "https://fal.ai/models/fal-ai/sam-3-1/video",
    task: "multi-object video segmentation",
  },
  "sam3-image": {
    category: "segmentation",
    defaultOptions: {
      apply_mask: true,
      max_masks: 3,
      output_format: "png",
    },
    description: "Segment image objects with text, point, or box prompts.",
    endpoint: "fal-ai/sam-3/image",
    inputField: "image_url",
    inputKind: "image",
    name: "SAM 3 Image",
    outputKeys: ["image", "masks", "metadata", "scores", "boxes"],
    price: { kind: "call", usd: 0.005 },
    pricing: "$0.005/request",
    sourceUrl: "https://fal.ai/models/fal-ai/sam-3/image",
    task: "promptable image segmentation",
  },
  "sam3-image-rle": {
    category: "segmentation",
    defaultOptions: {
      apply_mask: true,
      max_masks: 3,
    },
    description: "Segment image objects and return run-length encoded masks.",
    endpoint: "fal-ai/sam-3/image-rle",
    inputField: "image_url",
    inputKind: "image",
    name: "SAM 3 Image RLE",
    outputKeys: ["rle", "scores", "boxes", "metadata"],
    price: { kind: "call", usd: 0.005 },
    pricing: "$0.005/request",
    sourceUrl: "https://fal.ai/models/fal-ai/sam-3/image-rle",
    task: "promptable image segmentation to RLE",
  },
  "sam3-video": {
    category: "segmentation",
    defaultOptions: {
      apply_mask: true,
      detection_threshold: 0.5,
      prompt: "person",
      video_output_type: "X264 (.mp4)",
    },
    description: "Segment and track prompted objects across video frames.",
    endpoint: "fal-ai/sam-3/video",
    inputField: "video_url",
    inputKind: "video",
    name: "SAM 3 Video",
    outputKeys: ["video", "boundingbox_frames_zip"],
    price: { kind: "metered" },
    pricing: "$0.005/16 frames of video input",
    queued: true,
    sourceUrl: "https://fal.ai/models/fal-ai/sam-3/video",
    task: "promptable video segmentation",
  },
  "sam3-video-rle": {
    category: "segmentation",
    defaultOptions: {
      apply_mask: true,
      detection_threshold: 0.5,
      prompt: "person",
    },
    description: "Track prompted video objects and return RLE mask data.",
    endpoint: "fal-ai/sam-3/video-rle",
    inputField: "video_url",
    inputKind: "video",
    name: "SAM 3 Video RLE",
    // fal's video-rle endpoint no longer returns RLE data: its Output schema is
    // now identical to sam3-video's, so this entry differs only by endpoint.
    outputKeys: ["video", "boundingbox_frames_zip"],
    price: { kind: "metered" },
    pricing: "$0.005/16 frames of video",
    queued: true,
    sourceUrl: "https://fal.ai/models/fal-ai/sam-3/video-rle",
    task: "promptable video segmentation to RLE",
  },
  scribble: {
    category: "preprocess",
    description: "Turn an image into a scribble-style control map.",
    endpoint: "fal-ai/image-preprocessors/scribble",
    inputField: "image_url",
    inputKind: "image",
    name: "Scribble Preprocessor",
    outputKeys: ["image"],
    price: { kind: "metered" },
    pricing: "$0/compute-second listed by fal",
    sourceUrl: "https://fal.ai/models/fal-ai/image-preprocessors/scribble",
    task: "scribble preprocessing",
  },
  teed: {
    category: "preprocess",
    description: "Generate TEED edge maps from an input image.",
    endpoint: "fal-ai/image-preprocessors/teed",
    inputField: "image_url",
    inputKind: "image",
    name: "TEED Edge Preprocessor",
    outputKeys: ["image"],
    price: { kind: "metered" },
    pricing: "$0/compute-second listed by fal",
    sourceUrl: "https://fal.ai/models/fal-ai/image-preprocessors/teed",
    task: "edge preprocessing",
  },
  "zoe-depth": {
    category: "preprocess",
    description: "Generate ZoeDepth metric depth maps from an input image.",
    endpoint: "fal-ai/image-preprocessors/zoe",
    inputField: "image_url",
    inputKind: "image",
    name: "ZoeDepth Preprocessor",
    outputKeys: ["image"],
    price: { kind: "metered" },
    pricing: "$0/compute-second listed by fal",
    sourceUrl: "https://fal.ai/models/fal-ai/image-preprocessors/zoe",
    task: "depth preprocessing",
  },
} as const satisfies Record<string, FalToolConfig>;
